### ISSUE TITLE
download command continues execution after error

### ISSUE THREAD

**Issue by eode** [mkb79/audible-cli#104]
~If you specify a title / asin without a format selected, no error message is given, just `No new files downloaded."~

~Error messages indicating what is wrong would be nice.~

When using the download command, if no download option is specified, an error message shows up, but execution continues.

**Comment by mkb79** [comment]
Which version you are using? I've got an error message if I don't provide any of `--aax`, `--aaxc`, `--aax-fallback`, `--annotation`, `--chapter`, `--cover` or `--pdf`. 

 But I just noticed that the app should cancel execution after the error message. But somehow he doesn't.

**Comment by eode** [comment]
You're right, the issue is that it continues after the error message.
