### ISSUE TITLE
Unable to download Plus Catalog titles

### ISSUE THREAD

**Issue by smhmd** [mkb79/audible-cli#11]
is downloading Plus Catalog titles unsupported?
![image](https://user-images.githubusercontent.com/46059092/103462721-8c6dc700-4d27-11eb-8296-f1ce266b3198.png)

(Thanks for the API and CLI.)

**Comment by mkb79** [comment]
Audible Plus titles can be downloaded in „aaxc“ format with the `--aaxc` option.

**Comment by smhmd** [comment]
Works! Thanks. 

On a different note, @mkb79, would you be interested in working on a GUI app (in [Electron](https://www.electronjs.org/)) for Audible (with epub/pdf support and better UI)? If you'd like we can talk about it using [email](mailto:contact.simohamed@gmail.com) or [Disucssions](https://github.com/mkb79/audible-cli/discussions).

**Comment by mkb79** [comment]
I thought on a web app via Python django or flask in the past. But as a one men project, this idea is not realized yet. 

As far as I can read about Eletrcon, the code have to written in JS. My knowledge in JS is very basic, but I‘m willing to learn. If this is acceptable for you please contact me at mkb79@hackitall.de

**Comment by smhmd** [comment]
My knowledge of Python and Reverse Engineering is even more basic. So, I think it'll work great.
