### ISSUE TITLE
Paths in cmd_remove-encryption.py need to be str'ed

### ISSUE THREAD

**Issue by BlindWanderer** [mkb79/audible-cli#12]
As the title says, the various file objects need to be str'ed before used in cmd lists. On windows it breaks.

Gives the following error if you don't:

>   File "c:\python37\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "c:\python37\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\python37\lib\subprocess.py", line 1119, in _execute_child
    args = list2cmdline(args)
  File "c:\python37\lib\subprocess.py", line 530, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'WindowsPath' is not iterable

**Comment by mkb79** [comment]
Hmm, that sounds strange. The command running without any issue on my windows and debian machine. I will take a look on it.

**Comment by mkb79** [comment]
If testet on my windows machine again and it runs like it should.

If I understand your error message correct, the problem should not be a typing problem. The last line of your error says: `TypeError: argument of type 'WindowsPath' is not iterable`. The command should iter over a list of pathlib.Path objects but not over the pathlib.Path object itself. 

How you have entered your command and which options/flags you use?

**Comment by BlindWanderer** [comment]
Here's the change I made to make the first cmd list work. I applied the idea to all the others.

Original:
```
        cmd = ["ffmpeg",
               "-audible_key", audible_key,
               "-audible_iv", audible_iv,
               "-i", str(file),
               "-f", "ffmetadata",
               metafile]
```

Change:
```
        cmd = ["ffmpeg",
               "-audible_key", audible_key,
               "-audible_iv", audible_iv,
               "-i", str(file),
               "-f", "ffmetadata",
               str(metafile)]
```

I'm going to guess I'm not running as new a python version as you are and that's why this is happening.

**Comment by mkb79** [comment]
I‘ve implement your workaround in the plug-in command. And thank you very much for opening the issue. If code runs fine on my machines doesn’t guarantee that the code runs under other environments!

**Comment by BlindWanderer** [comment]
These two need it two:
```
               "-i", file,
               "-i", metafile_new,
```

**Comment by mkb79** [comment]
Thanks. I have overlooked this. But now it should be fixed.

**Comment by BlindWanderer** [comment]
Fixed in #https://github.com/mkb79/audible-cli/commit/93061312916b8556f173fe32d1906badf26e62d6
