### ISSUE TITLE
Api commands for getting info

### ISSUE THREAD

**Issue by tdguchi** [mkb79/audible-cli#126]
Hi, i was playing with api command, but i cant get it to give me the correct info.

I want to get all asin books on the catalog that are on AYCL and with "voice_description":"Castilian Spanish" 

Is there any way to get that? also... num_results its limited to 50, and page to 24, what if results are more than 1200? 

Also, knowing an asin, how can i delete it from my library? i know i have asked before about delete all library at once, this is only for given asin. its possible?

Thanks.

**Comment by mkb79** [comment]
Hi. How do you solve your issue?

**Comment by tdguchi** [comment]
oh sorry, I must have clicked close...

well, its partially solved, i have used:

audible api -m get /catalog/categories > categorias.txt

to get all categories, then, using a python scraper made by me, I have searched in all categories using selenium. 

using that i can select all aycl and spanish titles from all categories, an then (because one book could be in more than one category) y copied all asin and put them into a set (which only allows one copy of all elements) and then, used:

readarray -t asin < asin.txt;
for a in "${asin[@]}"; do       a='{"asin": "'"$a"'"}';     echo $a;     audible api -m put -b "$a" -i 4 library/item; done;

to add them to my library (+7500 books)

Now im downloading them, suffering the download limit everyday.... but, well, 3000 downloaded already.

Now i need your help to delete books knowing asin.

**Comment by mkb79** [comment]
You can remove an title with the `api` command like so `audible api -m delete library/item/{ASIN}/default_loan_ID`. This will work only with removable items like AYCL. Purchased items will does not work.

**Comment by tdguchi** [comment]
Thanks, all done now.
