### ISSUE TITLE
Help using api - Marketplaces

### ISSUE THREAD

**Issue by newhinton** [mkb79/audible-cli#129]
Hello, i would like to find out if and when new audiobooks will be available. Is it possible to use this api to get a list of upcoming releases that i can scrape? Thank you for your help!

**Comment by newhinton** [comment]
Thank you very much!

And sorry for opening this in the wrong repo, i guess this belongs more in the "library"-repo.

So i had a chance to experiment with your suggestions. The good news: they work and i can get books sorted by date. However, you led me a bit on a treasure-hunt, it is not `sort_by` but `product_sort_by` ;)

It seems that `products_since_timestamp` is not in use, i can pass arbitrary data to it without the api complaining. Other endpoints do complain.

Sadly, the category you provided is not really useful. It mainly results in books that are either in the past, or very shortly after the day the query was made.

There is [Coming Soon](https://www.audible.de/coming-soon), but i dont know if and how i would get the category-id for that. Using the API got me a lot of categories, but only the "public" ones. I also could not find your id. Is there an easy way to get those hidden id's?

**Comment by mkb79** [comment]
> So i had a chance to experiment with your suggestions. The good news: they work and i can get books sorted by date. However, you led me a bit on a treasure-hunt, it is not `sort_by` but `product_sort_by` ;)

The url is copy & paste from a request made with the original iOS Audible app. They use `sort_by` for the request. Maybe both params will work for this endpoint.  

> Is there an easy way to get those hidden id's?

I does not know any other way for now. But I will investigate more time in this. The Audible App does not have a `coming soon` section, so I can’t help you at this point.

**Comment by mkb79** [comment]
Good news. You can try out this url `https://api.audible.de/1.0/screens/audible-browse/search-ios?content_type=All&locales=de-DE&marketplace=AN7V1F1VY261K&origin_page=Home&publication_date=16290358031`. This will give you coming soon titles for the German marketplace. You can try it for other marketplaces with correct locales and marketplace params. Or you can try to let them out.

**Comment by mkb79** [comment]
You can use this to:

```python
…
r = client.get(
    "catalog/search",
    content_type="All",
    publication_date="16290358031",
    response_groups="product_desc"
)
```

You have to test out which response groups are valid for this endpoint. I doesn’t know that this endpoint exists before (and it seams to be deprecated but working)!

**Comment by mkb79** [comment]
Try to add `page` and/or `num_results` params like:

```python

r = client.get(
    "catalog/search",
    content_type="All",
    publication_date="16290358031",
    response_groups="product_desc",
    page=1,
    num_results=50
)
```

As far as I know the catalog/products endpoint uses page 0 for this first page, instead of page 1 how the library endpoint does. And the num_results for the catalog/products endpoint is limit is 50 (I think). Maybe this is equal for the catalog/search endpoint?!

**Comment by newhinton** [comment]
Sorry but those parameters do not work (for me). I tried them in any combination, but i only get the first 15 results. (Earlier i misscounted, it was 15)

I also tried others, like `results,products` or any from this part of the result:
```
    "result_count": {
        "max_displayable_result": "1200",
        "range_high": "15",
        "range_low": "1",
        "total": "4527"
    },
```

**Comment by mkb79** [comment]
I can verify that `num_results` not work. But page work but counting Beginns with 1. So next page is 2!

**Comment by newhinton** [comment]
> I can verify that `num_results` not work. But page work but counting Beginns with 1. So next page is 2!

Oh my, you are right! Sorry, i completely misunderstood.

I have now a working query, thank you so much for your work!
I can now use this to create calendar entries on books that i want to listen to!

**Comment by mkb79** [comment]
Glad to hear that. I could try to find out, if you can get more results per request. I will report here, if I find something.
