### ISSUE TITLE
Export Library fails due to httpx timeout

### ISSUE THREAD

**Issue by BlindWanderer** [mkb79/audible-cli#13]
library export fails with large libraries or slow transfers due to use of default httpx request timeout (5 seconds).

<strike>A fix is required in the underlying library audible-cli uses and possibly a change to audible-cli as well.</strike>

See https://github.com/mkb79/Audible/issues/36 for details

**Comment by mkb79** [comment]
Your problem should be only happens, when exporting your library. There I forgot to add (or remove) a timeout. He takes the default from audible.Client.__init__() which is 10 seconds. 

I have to choice if I add a higher timer to export library command only or to completely rebuild the package. What’s the best in your opinion?

**Comment by BlindWanderer** [comment]
Rebuilding doesn't sound like fun! So I guess the first option? I'd have written more than a workaround if I had a good clean solution :(

**Comment by mkb79** [comment]
I‘ve implement a timeout for library export command. Sorry for the delay. You can set a single request timeout for `models.Library.get_from_api` and `models.Library.aget_from_api` with the timeout request_params kwarg. The underlying `audible.Client.get` and `audible.AsyncClient.get` methods accept the timeout param and forward them to httpx.

**Comment by BlindWanderer** [comment]
#https://github.com/mkb79/audible-cli/commit/1a620c3744b71fb9502ea051e1e66af3f2be8351 causes the timeout to be passed in as a parameter of the request, not as a parameter to httpx.

I've tested the following change to [models.py](https://github.com/mkb79/audible-cli/blob/master/src/audible_cli/models.py) and it works:
```
    @classmethod
    async def aget_from_api(cls,
                            api_client: audible.AsyncClient,
                            locale: Optional[Locale] = None,
                            country_code: Optional[str] = None,
                            close_session: bool = False,
                            timeout = 10,
                            **request_params):

        if locale is not None and country_code is not None:
            raise ValueError("Locale and country_code provided. Expected only "
                             "one of them.")

        locale = Locale(country_code) if country_code else locale
        if locale:
            api_client.locale = locale

        if close_session:
            async with api_client:
                resp = await api_client.get("library", params=request_params, timeout=timeout)
        else:
            resp = await api_client.get("library", params=request_params, timeout=timeout)

        return cls(resp, auth=api_client.auth)
```

**Comment by mkb79** [comment]
If you use an instance of `audible.Client` or `audible.AsyncClient` the code works how I wrote it. 

The `get`, `post`, `delete` and `put` methods of them calls the `self._split_kwargs()` method to split special kwargs from params. But your code is much clearer for other.

**Comment by mkb79** [comment]
I‘ve implement your changes in my code. Sorry for the delay. Had to hard work on my kindle repo.

**Comment by BlindWanderer** [comment]
The speed at which you are responding to issues and comments is to be commended. It's much more typical for things to take months (and occasionally years) to be resolved. You do not need to apologize.

**Comment by BlindWanderer** [comment]
Fixed in #https://github.com/mkb79/audible-cli/commit/558eb3b330b4815a692ed8999f321285ac458577
