### ISSUE TITLE
Unable to run plugin subcommands

### ISSUE THREAD

**Issue by snowskeleton** [mkb79/audible-cli#132]
Maybe I'm overlooking something obvious. A fresh install of the latest audible-cli from github, running in Terminal on macOS, I always get this error message:
```
(.venv) snow@sleepy audible-cli % audible image-urls
Usage: audible [OPTIONS] COMMAND [ARGS]...
Try 'audible -h' for help.

Error: No such command 'image-urls'.
```
The same happens for `get-annotations`, `goodreads-transform`, `listening-stats`, and `remove-encryption`.

I've tried appending a `-h` to the end of some as well, with no noticeable change in behavior. I also tried prepending `cmd_` to the start of the plugin name with similar results.

What step am I missing in this process?

**Comment by mkb79** [comment]
Please run `audible -v DEBUG wishlist`. Then the plug-in dir which are used is shown in the cli. Then you can check if this dir contains any files.

**Comment by snowskeleton** [comment]
that worked! It was checking for plugins in `~/.audible/plugins`, but the `plugins` directory didn't exist inside `.audible`. I copied the contents of `plugin_cmds` to `~/.audible/plugins` and all is solved.

At some point I'll have to take a look at the code path for that. I feel like the plugins dir should get copied over during install.

**Comment by mkb79** [comment]
No problem at all. You can set an environment variable too. More can be read [here](https://github.com/mkb79/audible-cli#plugin-folder).

**Comment by mkb79** [comment]
> At some point I'll have to take a look at the code path for that. I feel like the plugins dir should get copied over during install.

I does not want to build in the plug-in commands. So these should be fully optional (maybe as an example for developing your own plug-in)!

**Comment by snowskeleton** [comment]
I read that spot in the README what feels like a dozen times, but only now did I correctly understand "...it will use a the plugins subdir of the **app dir.**" I kept reading that as the example plugin directory.
