### ISSUE TITLE
ignore-podcasts does not ignore Podcasts, hangs

### ISSUE THREAD

**Issue by tengelmeier** [mkb79/audible-cli#137]
Hi, 
it looks like the --ignore-podcasts option does not ignore podcasts and eventually hangs.
The bad thing about the hang is that there seems to be some resource exhaustion starting - after some time my mac gets sluggish and in the end it will reboot. 

Console:
error: Bad Request (400): Requested asin:XXXXXX is a non_audio asset with contentDeliveryType:PodcastParent

**Comment by mkb79** [comment]
@tengelmeier 
Thank you for opening this issue. Can you try out the new PR. This solves the issue by removing the podcast from list to proceed with when supplying the `--ignore-podcasts` option.

**Comment by tengelmeier** [comment]
The PR works for me.
