### ISSUE TITLE
Support for Spain 

### ISSUE THREAD

**Issue by adocampo** [mkb79/audible-cli#139]
Hello, when creating a config file through the wizard, I can't see any option for Spain
```
Please enter the country code (us, ca, uk, au, fr, de, jp, it, in): es
Error: 'es' is not one of 'us', 'ca', 'uk', 'au', 'fr', 'de', 'jp', 'it', 'in'.
```
Is it on the roadmap to provide support for audible.es?

**Comment by mkb79** [comment]
Hi. Which version of `audible-cli` you use? The latest version support `es` as you saw [here](https://github.com/mkb79/audible-cli/blob/6af331f43a657d822cd3f7a10a67f77462f61bd3/src/audible_cli/cmds/cmd_quickstart.py#L71)

**Comment by mkb79** [comment]
I'm closing this issue now. If the issue still exist, please reopen this issue.
