### ISSUE TITLE
Plugin Import from Plugin directory

### ISSUE THREAD

**Issue by BlindWanderer** [mkb79/audible-cli#14]
It would be nice to be able to have plugins be able to import things that exist in the plugin directory. 

I've been looking at how to modify plugin.py to do this. Looking at importlib I think there is probably a way to do it (seriously why is the api so busy if it doesn't allow for doing this?).

As a stopgap I'm using ``sys.path.append(str(pdir))`` just before the loop.

**Comment by mkb79** [comment]
Can you add the following to plugin.py at line 34:

`sys.path.insert(0, str(pdir.resolve()))` between

`pdir = pathlib.Path(plugin_dir)` and `cmds = [x for x in pdir.glob("cmd_*.py")]`

This must solve the problem. Please report to me so I can build in them.

**Comment by mkb79** [comment]
This doesn’t work for me. 

I could import with this workaround: Insert this line of code at the beginning of your script (before you import modules from plugin dir).

```python
import sys
import pathlib
pdir = pathlib.Path(__file__).parent.resolve()
sys.path.insert(0, str(pdir))
```

**Comment by PacoBell** [comment]
It doesn't seem to be detecting the included plugins I copied to the ~/.audible/plugins path. What am I missing?

For example:
```
pacobell@foo:~$ audible remove-encryption -i ./bar.aaxc
Usage: audible [OPTIONS] COMMAND [ARGS]...
Try "audible -h" for help.

Error: No such command "remove-encryption".
```
