### ISSUE TITLE
Downloading error: Please select an option what you want download.

### ISSUE THREAD

**Issue by Ithu123** [mkb79/audible-cli#151]
Runngin on Win10, i get the following error:

audible download --all
error: Please select an option what you want download.
Aborted!

I don't know what to do next. I tried reinstalling, but nothing changed.

**Comment by mkb79** [comment]
You have to specify, what you want to download. You can provide for e.g. `audible download --all --aaxc` to download audiobooks in aaxc format. For all available options you can run `audible download -h`.

**Comment by Ithu123** [comment]
Thank you very much.  I tried so many options, but I didn't realize that I had to specify the format. I am sorry.

I knew about the -h command, but i was too dumb. May i suggest adding an example usage of some sort to the readme.md? If you want you could use the following:

# Example Usage
To download all of your audiobooks in the aaxc format use:
```shell
audible download --all --aaxc
```
To download all of your audiobooks after the Date 2022-07-21 in aax format use: 
```shell
audible download --start-date "2022-07-21" --aax --all
```

**Comment by mkb79** [comment]
@Ithu123 
Thank you for your advice. I've added your example usage doc to the README. Is that okay with you?

**Comment by Ithu123** [comment]
Thats great! Thanks.
