### ISSUE TITLE
Windows Defender says there is a trojan in the Windows download of v0.2.5

### ISSUE THREAD

**Issue by philgoetz** [mkb79/audible-cli#159]
Microsoft Windows Defender says:

Trojan:Win32/Wacatac.B!ml
Alert level: Severe
Affected items:
containerfile: [snipped]\audible-cli\src\audible_win.zip
file: [shipped]\audible-cli\src\audible_win.zip->audible.exe

**Comment by mkb79** [comment]
@philgoetz 
Thanks for the information. This reminds me of issue #66. These file are created by a GitHub action using pyinstaller.
