### ISSUE TITLE
Problem with downloading covers

### ISSUE THREAD

**Issue by TheOkeland** [mkb79/audible-cli#16]
Hello, it seems that something prevents the download auf audiobook covers. Regardless, whether I specify the desired cover-size or not, the command faces with the simple statement
`Error in job:`

To be sure, I tested it with three different audiobooks identified by their asin, one for which I was able to download the cover some weeks ago.
Would it be possible that audible changed their API or might there have been a bug introduced in a recent update of the audible package for python?

**Comment by mkb79** [comment]
I‘ve tested downloading covers for all my audiobooks with my german Audible account. All running fine. 
I'm using this command: `audible download --all --cover`.

I've some questions:

1. Which audible-cli version you use?
2. Which OS and version you are running audible-cli?

**Comment by TheOkeland** [comment]
I am sorry to have bothered you. After rebooting my machine, the download of covers works again.  Possibly a bug in my shell environment as I had previously updated a bunch of python packages.

**Comment by mkb79** [comment]
Okay, fine to hear that.
