### ISSUE TITLE
Continue interrupted download

### ISSUE THREAD

**Issue by vwkd** [mkb79/audible-cli#169]
It would be great if a download would continue where it left off after it got interrupted. 

Since the files are large and can take some time to download, not having to download from scratch each time a connection is lost would be great.

**Comment by mkb79** [comment]
I'm currently working on this. Please take a look at [this](https://github.com/mkb79/audible-cli/discussions/163) discussion.

**Comment by vwkd** [comment]
Linked PR #164

**Comment by mkb79** [comment]
@vwkd 
Hi. Maybe you can test out PR #164 ? This resume aaxc files, if the download interrupts. If you have large audiobooks which can only be download in parts this should hopefully bring you now a correct message.can you verify that?

**Comment by vwkd** [comment]
@mkb79 I tried your PR on a few audiobooks and cancel and resume seems to work fine! I couldn't check the "download in parts" feature because it seems the audiobooks I have aren't large enough.
