### ISSUE TITLE
Support part download

### ISSUE THREAD

**Issue by jvanbruegge** [mkb79/audible-cli#187]
For long audiobooks (for me this only happens with the ~60h Rhythm of War by Brandon Sanderson), Audible does not allow a plain download. Using audible-cli gives this error:
```
Message: This title is not supported for full audio file download, please download individual parts.
```
I don't see a flag do so.
Thanks for the amazing cli though!

**Comment by mkb79** [comment]
These feature is already be implemented in the master branch but not released. If you want to use the feature, please install audible-cli from github with `pip install git+https://github.com/mkb79/audible-cli`.

**Comment by jvanbruegge** [comment]
oh, nice to hear!

**Comment by mkb79** [comment]
Do you have tried to download the book in AAX or AAXC format? As far as I know, this issue should only be appear on AAX files. AAXC files can be downloaded in one part, I believe!

**Comment by jvanbruegge** [comment]
For that one book neither worked. Some others worked with aaxc

**Comment by jvanbruegge** [comment]
Ok, I correct slightly, it does not work, but with a different error:
```
Message: Unspecified database error.
```

**Comment by mkb79** [comment]
Do you have this issue with the version from the master branch? If so, can you give me the ASIN of the book and the country code of the marketplace.

**Comment by jvanbruegge** [comment]
Tried it now with master, both aax and aaxc work

**Comment by mkb79** [comment]
Ah, that’s great. Thank you for your response.
