### ISSUE TITLE
Request: A way to skip podcasts

### ISSUE THREAD

**Issue by philgoetz** [mkb79/audible-cli#194]
Is it possible to identify podcasts, and skip downloading them?
I'm going to run out of hard drive space if all the episodes of all the podcasts I follow get loaded at once.
Plus it would take several days.

**Comment by mkb79** [comment]
@philgoetz 
You can add the option `--ignore-podcasts` to the download command. This should ignore them.

**Comment by philgoetz** [comment]
> @philgoetz You can add the option `--ignore-podcasts` to the download command. This should ignore them.

When I did that, the download crashed early, with:

> File /cygdrive/d/data/audio_/Audible/downloads/aaxc/Every_Man_a_Hero_A_Memoir_of_D-Day_the_First_Wave_at_Omaha_Beach_and_a_World_at_War-AAX_44_128.aaxc already exists. Skip download.
error: Bad Request (400): Requested asin:B0BVJMSZDR is a non_audio asset with contentDeliveryType:PodcastParent

**Comment by mkb79** [comment]
@philgoetz 
Oh, I see my mistake. I will fix these soon. In the meantime you can try to provide `--ignore-errors` option to the download command.

**Comment by mkb79** [comment]
I've released a [beta](https://github.com/mkb79/audible-cli/releases/tag/v0.3.2b1) which should solve some issues when downloading aax files or podcasts.
