### ISSUE TITLE
Undocumented options

### ISSUE THREAD

**Issue by philgoetz** [mkb79/audible-cli#197]
Whoops.  My mistake.  Please delete.

**Comment by mkb79** [comment]
@philgoetz 
Every command and subcommand has a `--help` or `-h` option, which will show you the command specific options and arguments. Each option must be provided to the level of the specific command.

Example:
If you call `audible -h` you can see several options. Among other things, there is a verbosity `-v` option. Now you can show only errors with `audible -v error [subcommand] [subcommand options]`. A full example is `audible -P "mkb79-us" -v error download --all --ignore-podcasts --aaxc --start-date "2024-03-01"`
