### ISSUE TITLE
Audible CLI not running

### ISSUE THREAD

**Issue by faiuwle** [mkb79/audible-cli#206]
Whenever I run this I get the following error:
```

Traceback (most recent call last):
  File "/home/ruth/.local/bin/audible", line 5, in <module>
    from audible_cli import main
  File "/home/ruth/.local/lib/python3.8/site-packages/audible_cli/__init__.py", line 5, in <module>
    from .cli import main, quickstart
  File "/home/ruth/.local/lib/python3.8/site-packages/audible_cli/cli.py", line 33, in <module>
    @plugins.from_entry_point(entry_points(group=PLUGIN_ENTRY_POINT))
TypeError: entry_points() got an unexpected keyword argument 'group'

```

Installation did not indicate that I was missing any dependencies.

**Comment by mkb79** [comment]
Thank you for open this issue. The exception is raised because you use an old version of the `importlib_metadata` package. How do you have installed `audible-cli`, do you use a venv, which OS do you use?

**Comment by faiuwle** [comment]
Ahh, thanks.  What version is needed, and can it be upgraded with pip?  I simply installed it via `pip install audible-cli` outside of a venv and only recently installed `importlib-metadata` for another package.  This is on Ubuntu 20.04, which I imagine is pretty old now, but I haven't used this particular install in a while.

**Comment by mkb79** [comment]
If I read the [changelog](https://importlib-metadata.readthedocs.io/en/latest/history.html) for importlib-metadatada correctly, you need at least v4.8.1. 

You can now run `pip install --upgrade importlib-metadata`. If the upgraded package conflicts with other packages you have already installed, I suggest you use a venv for audible-cli. If you need help for this step, please write here.

**Comment by faiuwle** [comment]
Thank you, after upgrading the package everything worked perfectly!

**Comment by mkb79** [comment]
Great to hear that. I'll close this issue now.
