### ISSUE TITLE
Support for Spain 'es'

### ISSUE THREAD

**Issue by carias-rh** [mkb79/audible-cli#21]
Is going to be available for the Spanish region anytime soon?
```
Enter a country code for the profile: es
Error: 'es' is not one of 'us', 'ca', 'uk', 'au', 'fr', 'de', 'jp', 'it', 'in'.
```

**Comment by mkb79** [comment]
I‘ve commit a change for the quickstart command. Spain should can be choiced  now.

**Comment by carias-rh** [comment]
That was fast! It's working like charm. Thank you :D
