### ISSUE TITLE
Titles saved with "empty" filenames when using JP marketplace

### ISSUE THREAD

**Issue by W-rakuda** [mkb79/audible-cli#22]
**Describe the bug**
When downloading from the JP marketplace, only ascii characters in the title of the book are used in the filename. 
For example, this results in a title named "ぼぎわんが、来る"
to be empty, named only as "-AAX_22_64.aaxc"
This makes it difficult to use the --all option, as all the files are named the same.

`audible library list` however, displays the book titles properly. 

**To Reproduce**
`audible download --all`
or
`audible download -a ASIN`

**Comment by mkb79** [comment]
I have opened a PR to solve the issue. Can you try out if this working for you?!

**Comment by W-rakuda** [comment]
Now the titles are saved with their ASIN if the title only contains non-ascii characters. However, if it contains a few, such as a number, that will be saved as the title instead. Some examples:

- **"ぼぎわんが、来る"**                                                                                         -> "B07PFRJN8X-AAX_22_64.aaxc"

- **"ハリー・ポッターと炎のゴブレット	Harry Potter and the Goblet of Fire"** -> 
   "_Harry_Potter_and_the_Goblet_of_Fire-AAX_22_64.aaxc"

- **"鹿の王　１"** -> "_1-AAX_44_128.aaxc"

My suggestion:
In the code I see you strip and clean up the names before using them as filenames. Maybe you could add a utf-8 mode for handling non-ascii filenames? 
I did a quick edit of the code, basically skipping most of the cleaning, and the filenames were saved correctly with the Japanese titles intact:
(Japanese titles can also be very short, sometimes only a single character)
My rough edit:
```
def full_title_slugify(self):
        valid_chars = "-_.() " + string.ascii_letters + string.digits 
        cleaned_title = unicodedata.normalize("NFKD", self.full_title)
        unicode_mode = True
        if not unicode_mode:
            cleaned_title = cleaned_title.encode("ASCII", "ignore")
            cleaned_title = cleaned_title.replace(b" ", b"_")
            slug_title = "".join(chr(c) for c in cleaned_title if chr(c) in valid_chars)
            if len(slug_title) < 2:
                slug_title = self.asin
        else:
            slug_title = cleaned_title
        return slug_title
```

**Comment by mkb79** [comment]
I‘ve rework filename mode. When downloading a file you can set the filename mode with `--filename-mode` or `-f` option. 

Current there are 4 modes available:

- ascii: Use only ascii letters
- asin_ascii: same as ascii but adds the asin in front of the filename
- unicode: Use unicode letters
- asin_unicose: same as unicode but adds the asin in front of the filename

Default is ascii.

**Comment by W-rakuda** [comment]
Ok, great! That should solve it. I think you probably don't need to normalize the Unicode text though, as that might produce unwanted changes in the filename (full-width numbers being converted to half-width in the case of Japanese, for instance) and shouldn't be necessary.
