### ISSUE TITLE
Unable to download aaxc files completely

### ISSUE THREAD

**Issue by yluvs** [mkb79/audible-cli#24]
Hello, 

It seems that as of yesterday, there's been some problem with downloading aaxc files. Only 919 bytes can be downloaded. This happens to both purchased titles and plus titles.

Could you please look into this problem?

Thank you very much.

P.S. I am using the latest version.

**Comment by mkb79** [comment]
I'll look into this. Seams the same issue like [here](https://github.com/rmcrackan/Libation/issues/79).

**Comment by yluvs** [comment]
Wow! I really appreciate your quick response to my inquiry. Thank you so much for looking into this.

I was also wondering if it would be okay to take this opportunity to make a couple of feature requests. If not, I'll open a new issue. ;)

**Comment by mkb79** [comment]
You can write your feature requests here, no problem ;)!

**Comment by mkb79** [comment]
The Audible App for mobile devices sends a `requestID` cookie since long time. These cookie isn't send with my app. 

I think these cookie was not check in the past by Amazon. But now. These explains why older Audible Apps for mobile devices have no problems (they send them already)!

The cookie looks like: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:1627xxxxxx! The first part is the `license_id` from licenserequest response body. The  second part is the Unix timestamp of the `X-Amz-Date` header from the licenserequest response!

I'll try this out but I will need some time. I'm on vacation for some days.

**Comment by yluvs** [comment]
No problem, please take your time. I suppose that in the mean time, we can still download the aaxc files using the mobile device and decrypt them with the info provided by the voucher files.

As for my feature requests, if it's not too much trouble, could you please consider adding support for podcast download? It appears to me that audible-cli cannot locate the podcast titles in our libraries for the time being. The system always gives me titles not found in the library message. I've tried both podcast title asin and individual episode aisn, and neither of them worked.

My second request is that I would be very grateful if chapter titles could be made optional when we download the voucher files. For instance, we would need to add a certain command should we require this information. I really miss the old days when the voucher files were small in size and the key and iv were in the first two lines.

As always, thank you very much for this wonderful programme and all the efforts you put into it. 👍

**Comment by mkb79** [comment]
Found the real reason for download errors and fixed it in version.

**Comment by mkb79** [comment]
Your 2nd feature request is no problem. I can solve this with an additional command. How to display podcast correctly I must take a look how to get them!

**Comment by yluvs** [comment]
Splendid! That was super fast! Thanks a lot for solving the aaxc download problem and fulfilling my second request. I am so excited about the new version! :D

Please take as much time as you need with the podcasts. I can wait forever for that. ;)
