### ISSUE TITLE
Misplaced parenthesis

### ISSUE THREAD

**Issue by TpmKranz** [mkb79/audible-cli#26]
Not really worth a pull request, but something I needed to fix locally to be able to proceed.
The closing parenthesis from line 161 should be moved before the comma in line 160, otherwise the kwarg for `build_auth_file` in line 161 looks like a kwarg to `.get`:

https://github.com/mkb79/audible-cli/blob/b7af1b40f00e8027effe3a71e909809def63f12c/src/audible_cli/cmds/cmd_quickstart.py#L160-L161

**Comment by mkb79** [comment]
Thank you for this Information. I‘ve updated the package.
