### ISSUE TITLE
[Feature] Make 'Accept' default action

### ISSUE THREAD

**Issue by newhinton** [mkb79/audible-cli#28]
When downloading an audiobook, and -y is not added as a parameter, the user is asked to confirm. I suggest switching from [y/N] to [Y/n]. This removes the necessity to add an additional y, because i assume that the tool finds the proper books more often than it produces errors which need to be aborted. This is a personal preference, but i think it could be better this way.

**Comment by mkb79** [comment]
Thanks for your feature request. I've made 'Y' as default answer now!
