### ISSUE TITLE
Getting started instructions are unclear

### ISSUE THREAD

**Issue by rmcrackan** [mkb79/audible-cli#29]
I'm at a loss. I must be missing something fundamental. Cannot get this to work at all. Steps I took on Windows 10:

installed python 3.9

installed pip and wheel

open cmd window

```
C:\Dev\New folder>git clone https://github.com/mkb79/audible-cli.git
Cloning into 'audible-cli'...
```
...
```
C:\Dev\New folder>cd audible-cli

C:\Dev\New folder\audible-cli>pip install .
Processing c:\dev\new folder\audible-cli
  DEPRECATION: A future pip version will change local packages to be built in-place without first
copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test
your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at
https://github.com/pypa/pip/issues/7555.
```
...
```
C:\Dev\New folder\audible-cli>audible-quickstart
'audible-quickstart' is not recognized as an internal or external command,
operable program or batch file.

C:\Dev\New folder\audible-cli>python audible-quickstart
python: can't open file 'C:\Dev\New folder\audible-cli\audible-quickstart': [Errno 2] No such file or directory

C:\Dev\New folder\audible-cli>python -c audible-quickstart
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'audible' is not defined

C:\Dev\New folder\audible-cli>audible -h
'audible' is not recognized as an internal or external command,
operable program or batch file.

C:\Dev\New folder\audible-cli>python
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

>>> audible-quickstart
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'audible' is not defined

>>> help
Type help() for interactive help, or help(object) for help about object.

>>> audible -h
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'audible' is not defined

>>> audible quickstart
  File "<stdin>", line 1
    audible quickstart
            ^
SyntaxError: invalid syntax

>>> -c audible quickstart
  File "<stdin>", line 1
    -c audible quickstart
       ^
SyntaxError: invalid syntax

>>> audible audible-quickstart
  File "<stdin>", line 1
    audible audible-quickstart
            ^
SyntaxError: invalid syntax

>>>
```

**Comment by mkb79** [comment]
Please try `python -m audible_cli`. Mayen that helps for the Moment. I think something is going wrong registering the `audible` and `aAudible- quick start commands. 

Maybe you should change the folder away from the git clone folder.

**Comment by rmcrackan** [comment]
Ah, the -m flag did it.

Documentation suggestions:

* mention the -m flag
* calls are "audible_cli" rather than "audible"
* The json file is not where the readme says it will be. Mine went into the deeply cryptic C:\Users\[user]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\Local\Audible

**Comment by mkb79** [comment]
On my windows and Linux machines all running as aspected. That's strange to hear. Will look at this.

**Comment by rmcrackan** [comment]
To reproduce:

On a windows machine: uninstall python. Then in cmd, type python. It will open the Microsoft Store's page for python. Install from here. I'm not a fan of how Microsoft Store installs things but it's the easiest way to get a non-technical person to install python.

**Comment by mkb79** [comment]
Oh, this explains a lot. Installing python from Microsoft Store results in running in a sort of sandbox (as far as I know)! That is the reason for the diverted location for the config dir.

**Comment by rmcrackan** [comment]
Agreed. I'm mentioning in case you want to include it also in documentation.

I couldn't find it anywhere. When I used your program to open a config file for editing, I could see where it lived by using my text editor.
