### ISSUE TITLE
External browser option for username?

### ISSUE THREAD

**Issue by rmcrackan** [mkb79/audible-cli#30]
I can successfully login using the external browser option with email. I did not see an option for how to do this with the old pre-amazon usernames. Is that possible?

**Comment by mkb79** [comment]
Yeah this should be possible. If you run the quickstart command you can select external_login and then enter the Audible username and password.

**Comment by rmcrackan** [comment]
Thanks

**Comment by mkb79** [comment]
Oh my mistake. It's not possible yet but I will implement this now.

**Comment by rmcrackan** [comment]
Much thanks. Please comment here when complete.

**Comment by mkb79** [comment]
If updated `audible-cli` now. You can login with a pre-amazon account.

**Comment by rmcrackan** [comment]
That was fast. Thank you.
