### ISSUE TITLE
Can we add this to pypi?

### ISSUE THREAD

**Issue by luscoma** [mkb79/audible-cli#34]
Is there a reason this isn't in pypi?  Mostly curious since it's already packaged.

**Comment by mkb79** [comment]
I started this project without knowledge in programming a cli with Python. So this was previously a testing package. In the meantime `audible-cli` runs fine for me. But no one asking to add this to pypi. 

I've uploaded it now! You can find it [here](https://pypi.org/project/audible-cli/)!
