### ISSUE TITLE
Problem with downloading aaxc files

### ISSUE THREAD

**Issue by yluvs** [mkb79/audible-cli#4]
Hi,

Thank you very much for developing this great tool! I was wondering if you could please advise me on a problem I encountered with downloading Audible Plus aaxc files.

When I used the command below, it always gave me an error message.

C:\Users\xxx\audible-cli>audible download --aaxc --asin B086XJ4CK7
Error in job: Unterminated string starting at: line 1 column 386 (char 385)

And If I don't use the aaxc option, I would end up with an aax file less than 1 KB.

C:\Users\xxx\audible-cli>audible download --asin B086XJ4CK7
The_Gentleman_from_Peru-LC_128_44100_stereo.aax: 100%|█| 33.0/33.0 [00:00<00:00
File C:\Users\xxx\audible-cli\The_Gentleman_from_Peru-LC_128_44100_stereo.aax downloaded to C:\Users\xxx\audible-cli in 0:00:01.131236

Did I do something wrong here? :P Would be very grateful if you could please help me with this problem. Thank you. :)

**Comment by mkb79** [comment]
Is this a audible plus book or you are purchased this one? Your error sounds like naming conflicts with filename and windows.

**Comment by mkb79** [comment]
I‘ve open a pull request. Can you try this changes and report me?!

**Comment by yluvs** [comment]
Thanks very much for the speedy reply.

I've applied the changes, but still got the same error message. I think this issue might be audible-plus-specific, because I haven't had any problems downloading books I purchased in aaxc format so far.

**Comment by mkb79** [comment]
I‘ve added some line of codes. If you try this, you will get a api response with `customer rights`. Can you send me this informations please?!

After this, you will get printed out the license request response data. Please don’t post this data here, but copy and paste them for later purpose. But you can tell me, if you got an offline download link in the response data.

**Comment by mkb79** [comment]
I‘ve solved the problem. The error was on decrypting the voucher. The decryption was not is not complete. The last bytes where left. So a conversion from string to python dict with json thrown an error. The problem is ?maybe? the pyaes module. I‘ve build-in a workaround and it worked for me. I‘ll upload this later or switch to another aes module (I‘m limited to pure python packages)!

**Comment by mkb79** [comment]
I‘ve updated the `audible` package now to v0.4.3 and the `issue-4` branch from this package. Can you try if this works for you! It worked for me.

**Comment by yluvs** [comment]
Yes, I just upgraded the audible package to v.0.4.4 and it worked beautifully!! Thank you so much for your hard work! :D

**Comment by mkb79** [comment]
No problem at all.
