### ISSUE TITLE
Detection of invalid downloads

### ISSUE THREAD

**Issue by taxilian** [mkb79/audible-cli#47]
I don't expect this comes up a lot, but I have quite a few (738) audible books in my library which I just downloaded using this tool (which is awesome, btw -- thank you SO MUCH for this. it is *fantastic*)

I had 343 books which ended up as text files with these contents:

```
This audio format is not supported for the title. Please download in another audio format.
```

I also had 15 files at the end with the contents: 

```
No Library Record Found for user.
```

My guess on the first is that it may have to generate the file if it's the first time you've accessed it asking for an `aax` file, and the second is probably just a bug on their side which I saw by downloading so many files at once.  I deleted all of those files and am trying again and it seems to be getting them -- though we'll see if I still end up with some of them afterwards.

At any rate it'd be nice if the tool could detect that it wasn't an AAX file (or even just that it's too small -- both of these types were both under 100 bytes in size) and either not keep the file or else automatically retry.

**Comment by mkb79** [comment]
Thank you for submitting this issue. I think you are downloading them as aax file? If yeah, can you try to download some of them as AAXC?

**Comment by mkb79** [comment]
Can you give me 2 or 3 asins from each group, so I can take a look on it?

**Comment by taxilian** [comment]
Hi,

The problem is not consistent -- it failed the first time, but when I tried it again it downloaded them just fine. I was downloading AAX files, but they are all relatively normal books.

**Comment by mkb79** [comment]
Okay. Then I revise the file download part. It is best to check which status code the server sends when requesting a download. Will implement this with the next release.

**Comment by mkb79** [comment]
I‘ve created a PR which contains some improvements to detect, if a download is okay. Can you try this out?

**Comment by taxilian** [comment]
At this point I've already downloaded my full library, so testing would require me to re-download it which I don't have time/disk space to do right now, but those changes look reasonable to me.
