### ISSUE TITLE
Creating a .voucher file

### ISSUE THREAD

**Issue by normal1ze** [mkb79/audible-cli#49]
Hello. I am having a little trouble finding an example of how to create the voucher file. 

I have a voucher.json file with the `key` and `iv` params, but it seems to decode I need a properly formatted .voucher file with `content_license` param etc. 

Would you be able to point me in the right direction with this?

**Comment by normal1ze** [comment]
Oh sorry I think I have it. I just wrote the response from the license request into the file that was decrypted for the voucher into one `.voucher` file. I hope this was the right direction. Seems to work. Let me know if not. 

Here's what I did:

```
voucher_file = filename.with_suffix('.voucher')
voucher__keys_file = filename.with_suffix(".json")

decrypted_voucher = decrypt_voucher_from_licenserequest(auth, data)

data['content_license']['license_response'] = decrypted_voucher
voucher_file.write_text(json.dumps(data, indent=4))
voucher__keys_file.write_text(json.dumps(decrypted_voucher, indent=4))
```

**Comment by normal1ze** [comment]
Wrong repo. Meant to post in Audible

**Comment by mkb79** [comment]
> Oh sorry I think I have it. I just wrote the response from the license request into the file that was decrypted for the voucher into one `.voucher` file. I hope this was the right direction. Seems to work. Let me know if not.
> 
> Here's what I did:
> 
> ```
> voucher_file = filename.with_suffix('.voucher')
> voucher__keys_file = filename.with_suffix(".json")
> 
> decrypted_voucher = decrypt_voucher_from_licenserequest(auth, data)
> 
> data['content_license']['license_response'] = decrypted_voucher
> voucher_file.write_text(json.dumps(data, indent=4))
> voucher__keys_file.write_text(json.dumps(decrypted_voucher, indent=4))
> ```

Yeah, this work. In practice you only need the decrypted voucher (key/iv pair) to decrypt aaxc files. All other data in the `data` dictionary contains additional information.
