### ISSUE TITLE
Podcast support

### ISSUE THREAD

**Issue by 3456091** [mkb79/audible-cli#58]
Thanks for this. Any pointers on how to download a podcast from Audible?

I can extract from the Android app the aaxc file and an $ASIN.companion file which contains a value for "acr", but am unsure how to proceed. The app logs contain a license_id and Key-Pair-Id. Can I cobble together these values to decrypt the file? :-)

**Comment by mkb79** [comment]
Hi,

podcasts can be downloaded very easy. I have deactivate this in `audible-cli`because I don't need this and no one asked me. 

If you can extract the license response you need your device serial, your customer id, the device type and the asin. Except the last all data are obtained at device registration. So you have to capture all https traffic on your Android device when you login with your Audible App.

**Comment by 3456091** [comment]
Thank you. I've hacked together something by using your API examples, but an option in the CLI would be wonderful.

**Comment by mkb79** [comment]
Hmm, I don’t think it is a good idea to implement this in the `download` sub-command. I would create a new `podcast` sub-command. What you are thinking about this?

**Comment by 3456091** [comment]
That would work, too. 

The first part is gathering the ASINs of the episodes. I've presumably missing something obvious, but I can't find the appropriate endpoint to enumerate the episode ASINs for a given series ASIN. I'm currently screen-scraping the HTML for this.

Secondly, following a podcast adds it to your library, but the download subcommand doesn't see it so can't download it.

Thirdly, the podcasts I've tried don't have episode-level metadata containing the podcast name, so I'm having to fix this manually.

But, as you say, the Python library manages the download of the podcasts correctly if you find the episode ASINs.

A podcast subcommand that either downloaded all of the podcasts you follow, or all episodes for a given series ASIN, would be wonderful.

**Comment by mkb79** [comment]
Yeah, the `models.LibraryItem._is_downloadable` exclude Periodicals such as podcasts. 


You can get all asins for your podcasts like so:

```python
r = client.get(
    "library",
    num_results=1000,
    response_groups="product_desc, pdf_url, media, product_attrs, relationships"
)
for i in r["items"]:
    if i["content_delivery_type_"] == "Periodical":
        print(i["title"])
        print(i["asin"])
```

You can get all episodes for a podcast like so:

```python
r = client.get(
    "library",
    parent_asin=asin  # the asin for the podcast,
    response_groups="product_desc, pdf_url, media, product_attrs, relationships"
)

for i in r["items"]:
    if i["content_delivery_type_"] == "Periodical":
        print(i["title"])
        print(i["asin"])
```

**Comment by 3456091** [comment]
Thank you. :-)

**Comment by mkb79** [comment]
@3456091 
Hi. I‘ve implemented a podcats download function in the development branch now. Simply add `--resolve-podcats` flag to the download command.

**Comment by 3456091** [comment]
Thank you. A couple of problems, which I've illustrated using actual ASINs so you can recreate them.

`audible download --resolve-podcasts --asin B09RGKLPXC --aaxc
Error in job: Bad Request (400): Requested asin:B09RGKLPXC is a non_audio asset`

`audible download --resolve-podcasts --asin B08JK17J86 --aax
Error in job: 'NoneType' object is not iterable`

I can't see any debug output to send, but note that in the UK catalogue, which I'm using, the main podcast ASIN has a `content_delivery_type` of `PodcastParent`, and, on the library/$ASIN endpoint, at least the individual episodes have a `content_delivery_type` as `None`. (This is using your Audible module).

**Comment by mkb79** [comment]
You are using the parent asin to download the episodes. This doesn't work at this moment. I will implement this before I release v0.1.0. You can use the `-t "TITLE OF THE PODCAST"` instead of the `--asin` option in the meantime.

**Comment by mkb79** [comment]
You are meaning the UK catalog or UK library?

**Comment by 3456091** [comment]
The UK catalogue.

**Comment by 3456091** [comment]
> You are using the parent asin to download the episodes. This doesn't work at this moment. I will implement this before I release v0.1.0. You can use the `-t "TITLE OF THE PODCAST"` instead of the `--asin` option in the meantime.

```
$ audible download --resolve-podcasts --title 'Am I Dating a Serial Killer' --aaxc

Found the following matches for 'Am I Dating a Serial Killer'
+---------+-----------------------------+------------+
| % match | title                       |    asin    |
+---------+-----------------------------+------------+
|  100.0  | Am I Dating a Serial Killer | B09RGKLPXC |
+---------+-----------------------------+------------+
Proceed with this audiobook(s) [Y/n]: y
Error in job: Bad Request (400): Requested asin:B09RGKLPXC is a non_audio asset
```
```
$ audible download --resolve-podcasts --title 'Algorithms at Work' --aaxc

Found the following matches for 'Algorithms at Work'
+---------+--------------------+------------+
| % match | title              |    asin    |
+---------+--------------------+------------+
|  100.0  | Algorithms at Work | B09QXPK5J6 |
+---------+--------------------+------------+
Proceed with this audiobook(s) [Y/n]: y
Error in job: Bad Request (400): Requested asin:B09QXPK5J6 is a non_audio asset
```

**Comment by 3456091** [comment]
I can confirm that downloading individual podcast episodes by ASIN now works.

I suspect the most common use case is downloading an entire podcast, in which case you will know the podcast and episode names. I think it's OK for episodes downloaded individually not to include the podcast name in their title. 

So the next step is to detect when the ASIN refers to a podcast series, then download the individual episodes?

**Comment by mkb79** [comment]
I've commited a change for naming podcast episodes. Can you try the download command with the `--title/-t` option?

**Comment by 3456091** [comment]
Entering the title of a podcast finds the podcast itself and an episode of that podcast, errors on the former, and downloads the latter:

```
$ audible download --resolve-podcasts --title 'Solving the Black Dahlia' --aaxc

Found the following matches for 'Solving the Black Dahlia'
+---------+----------------------------------+------------+
| % match | title                            |    asin    |
+---------+----------------------------------+------------+
|  100.0  | Solving the Black Dahlia         | B09Q3NMSYY |
|  100.0  | Solving the Black Dahlia Trailer | B09Q3P7F9Q |
+---------+----------------------------------+------------+
Proceed with this audiobook(s) [Y/n]: y
Error in job: Bad Request (400): Requested asin:B09Q3NMSYY is a non_audio asset
Voucher file saved to /tmp/audible-cli/Solving_the_Black_Dahlia_Trailer-AAX_44_128.voucher.
/tmp/audible-cli/Solving_the_Black_Dahlia_Trailer-AAX_44_128.aaxc: 100%|██████████████████████████████████████████████████████████████████| 989k/989k [00:00<00:00, 2.20MB/s]
File /tmp/audible-cli/Solving_the_Black_Dahlia_Trailer-AAX_44_128.aaxc downloaded to /tmp/audible-cli in 0:00:00.602447.
```

Given a title of one of that podcast's episodes, it correctly downloads that episode:

```
$ audible download --resolve-podcasts --title 'Episode 1: Photo Evidence' --aaxc

Found the following matches for 'Episode 1: Photo Evidence'
+---------+---------------------------+------------+
| % match | title                     |    asin    |
+---------+---------------------------+------------+
|  100.0  | Episode 1: Photo Evidence | B09Q3NSKHQ |
+---------+---------------------------+------------+
Proceed with this audiobook(s) [Y/n]: y
Voucher file saved to /tmp/audible-cli/Episode_1_Photo_Evidence-AAX_44_128.voucher.
/tmp/audible-cli/Episode_1_Photo_Evidence-AAX_44_128.aaxc: 100%|████████████████████████████████████████████████████████████████████████| 43.3M/43.3M [00:24<00:00, 1.88MB/s]
File /tmp/audible-cli/Episode_1_Photo_Evidence-AAX_44_128.aaxc downloaded to /tmp/audible-cli in 0:00:24.289358.
```

Given the ASIN of the same episode it correctly infers that episode has already been fetched:

```
$ audible download --resolve-podcasts --asin B09Q3NSKHQ --aaxc
File /tmp/audible-cli/Episode_1_Photo_Evidence-AAX_44_128.voucher already exists. Skip download.
File /tmp/audible-cli/Episode_1_Photo_Evidence-AAX_44_128.aaxc already exists. Skip download.
```

**Comment by mkb79** [comment]
I've reworked the `download` subcommand now. If you provide the asin or the title of the parent podcast item (or use the `--all` flag) now all episodes will be downloaded without the `--resolve-episodes` flag. The flag is needed only, if you want to download a specific episode of a podcast.

**Comment by 3456091** [comment]
That looks to work well. It meets my needs.

I think long term a better file naming strategy could be considered. For a podcast, putting the episodes in a directory named for the podcast is probably the right approach, but for now --output-dir can be used for this purpose.

**Comment by mkb79** [comment]
Thank you for your idea. I think I will implement subdirs for podcasts!

**Comment by 3456091** [comment]
I tried out your change and it looks to work well.

One thing to consider is adding the episode number to the filename so they can be played in order. This would either consist of adding the index of the ASIN in the episode array to the filename, or extracting the sequence number from the metadata `Product ID` field. As an example of the latter:

```
$exiftool -ProductID Gutfull_What_to_Eat_for_a_Happy_Gut/*aaxc
======== Gutfull_What_to_Eat_for_a_Happy_Gut/Gutfull_What_to_Eat_for_a_Happy_Gut_Ep_10_Ouch-AAX_44_128.aaxc
Product ID                      : PC_313M_000010UK
======== Gutfull_What_to_Eat_for_a_Happy_Gut/Gutfull_What_to_Eat_for_a_Happy_Gut_Ep_1_What_the_Fork-AAX_44_128.aaxc
Product ID                      : PC_313M_000001UK
======== Gutfull_What_to_Eat_for_a_Happy_Gut/Gutfull_What_to_Eat_for_a_Happy_Gut_Ep_2_A_Tale_of_Two_Meals-AAX_44_128.aaxc
Product ID                      : PC_313M_000002UK
======== Gutfull_What_to_Eat_for_a_Happy_Gut/Gutfull_What_to_Eat_for_a_Happy_Gut_Ep_3_Youre_Not_Alone-AAX_44_128.aaxc
Product ID                      : PC_313M_000003UK
======== Gutfull_What_to_Eat_for_a_Happy_Gut/Gutfull_What_to_Eat_for_a_Happy_Gut_Ep_4_Diversity_Is_King-AAX_44_128.aaxc
Product ID                      : PC_313M_000004UK
======== Gutfull_What_to_Eat_for_a_Happy_Gut/Gutfull_What_to_Eat_for_a_Happy_Gut_Ep_5_To_Eat_or_Not_to_Eat-AAX_44_128.aaxc
Product ID                      : PC_313M_000005UK
======== Gutfull_What_to_Eat_for_a_Happy_Gut/Gutfull_What_to_Eat_for_a_Happy_Gut_Ep_6_Its_Not_You_Its_Me-AAX_44_128.aaxc
Product ID                      : PC_313M_000006UK
======== Gutfull_What_to_Eat_for_a_Happy_Gut/Gutfull_What_to_Eat_for_a_Happy_Gut_Ep_7_Thats_Mental-AAX_44_128.aaxc
Product ID                      : PC_313M_000007UK
======== Gutfull_What_to_Eat_for_a_Happy_Gut/Gutfull_What_to_Eat_for_a_Happy_Gut_Ep_8_Its_All_Hot_Air-AAX_44_128.aaxc
Product ID                      : PC_313M_000008UK
======== Gutfull_What_to_Eat_for_a_Happy_Gut/Gutfull_What_to_Eat_for_a_Happy_Gut_Ep_9_Blocked__Burned-AAX_44_128.aaxc
Product ID                      : PC_313M_000009UK
``` 

In the _B08JK17J86_ podcast, all episodes fail to download as follows:

```
Error downloading /tmp/audible-cli/Bhante_Vimalaramsi/Bhante_Vimalaramsi_Guided_Meditation_for_Observing_the_Jhanas__Factors_1-4-MPEG.aaxc. Wrong content type. Expected type(s): ['audio/aax', 'audio/vnd.audible.aax']; Got: audio/mpeg; Message: Unknown
```

On the Audible website they open in a video player, but the ones I examined don't have any video. Just badly encoded, I assume. An episode that exhibits this behaviour is _B09P9WBZ9C_,

I tried downloading this podcast to check whether podcasts with lots of episodes---this has 100---were downloaded in their entirety. For this one I got 10 voucher files and no AAXCs.

**Comment by mkb79** [comment]
Thank you for you information. I‘ve tested the podcast B08JK17J86 myself. 

I found out, that the podcast episodes does not contain available_codecs. But they can be downloaded via API as MPEG-file; these needs some rework on my package!

Next I found is, that resolve a library item (e.g. a podcast) gives me max. 10 items. That is a problem, if there are more than 10 children elements! Will look deeper into these.

**Comment by mkb79** [comment]
That's really strange. If I use asin B08XV587F4 from germany marketplace I got all 297 episodes. Can you try out another podcast from uk marketplace with more than 10 episodes?

**Comment by 3456091** [comment]
I tried with _B09NB1PBRN_ and correctly got 15 episodes. For _B08YD3RC7Y_, I got 10 of 20 episodes. I got all 17 episodes of _B09HRC9HMV_. I tried the 522-episode _B08JK197WJ_, but ran into the content-type issue described above. Still experimenting.

**Comment by 3456091** [comment]
As of 02089ea9274f418fdfee66c1bfdaa750d91742dc , I confirm that I get 10 episodes of _B08JK17J86_ downloaded. Given that the episodes download as MP3s, the _.voucher_ files are useless. Perhaps a warning should be given to the effect of the --aaxc switch was supplied, but has been ignored?

**Comment by mkb79** [comment]
I‘ve created a workaround for the 10 children limit issue. I will commit this after some fine tuning!

The `--aaxc` flag download books with the licenserequest method from the AudibleAPI. In most cases these are aaxc files, but not at all. So these flag was not ignored!!! To not confuse the user I would let these untouched. 

Voucher files are useless for mp3 files. But I would keep them, because these files contain some useful metadata (e.g. chapter information)! For some reason, these metadata can't obtained by the `--chapter` flag for some items (e.g. Podcasts in mp3 format)!

**Comment by mkb79** [comment]
@3456091 I've commit my workaround now. This should let you download all episodes of a podcast!

**Comment by 3456091** [comment]
> The --aaxc flag download books with the licenserequest method from the AudibleAPI. In most cases these are aaxc files, but not at all. So these flag was not ignored!!! To not confuse the user I would let these untouched.

I merely meant that the _download_ subcommand errors out when you fail to supply either --aax or --aaxc, but in these cases neither flag controls what you actually get. To my mind, if a user requests a specific format, it should be an error if that format can't be downloaded. This would imply a default behaviour of not requiring any format flag, and just downloading the best format for the given ASIN. 

> @3456091 I've commit my workaround now. This should let you download all episodes of a podcast!

This seems to work well. I'll let you know if I find any bugs. Thanks again.

**Comment by mkb79** [comment]
> I merely meant that the download subcommand errors out when you fail to supply either --aax or --aaxc, but in these cases neither flag controls what you actually get. To my mind, if a user requests a specific format, it should be an error if that format can't be downloaded. This would imply a default behaviour of not requiring any format flag, and just downloading the best format for the given ASIN.

You can use the download command without the `--aax` or `--aaxc` flag. I you want to download the cover only, simply use the `--cover` flag without the former. I‘m thinking about this!

**Comment by devnoname120** [comment]
@mkb79 It looks like specifying either `--aax` or `--aaxc` is **required** but then it downloads MP3 anyway. Is this a regression?

```shell
ubuntu@ubuntu:~/hpmor$ audible download --asin B08JKF4XHD
Usage: audible download [OPTIONS]
Try 'audible download -h' for help.

Error: Please select an option what you want download.
```


```shell
ubuntu@ubuntu:~/hpmor$ audible download --asin B08JKF4XHD --aaxc
Voucher file saved to /home/ubuntu/hpmor/Harry_Potter_and_The_Methods_of_Rationality_Audiobook/Harry_Potter_and_The_Methods_of_Rationality_Audiobook_Significant_Digits_(Chapter_3)_(Pt_1)-MPEG.voucher.
Voucher file saved to /home/ubuntu/hpmor/Harry_Potter_and_The_Methods_of_Rationality_Audiobook/Harry_Potter_and_The_Methods_of_Rationality_Audiobook_Significant_Digits_(Chapter_1)-MPEG.voucher.
Voucher file saved to /home/ubuntu/hpmor/Harry_Potter_and_The_Methods_of_Rationality_Audiobook/Harry_Potter_and_The_Methods_of_Rationality_Audiobook_Significant_Digits_(Chapter_2)-MPEG.voucher.
Harry_Potter_and_The_Methods_of_Rationality_Audiobook_Significant_Digits_(Chapter_3)_(Pt_1)-MPEG.mp3: 100%|███████████████████████████| 42.2M/42.2M [00:06<00:00, 6.60MB/s]
File /home/ubuntu/hpmor/Harry_Potter_and_The_Methods_of_Rationality_Audiobook/Harry_Potter_and_The_Methods_of_Rationality_Audiobook_Significant_Digits_(Chapter_3)_(Pt_1)-MPEG.mp3 downloaded in 0:00:06.675025.nality_Audiobook_Significant_Digits_(Chapter_2)-MPEG.mp3:  90%|██████████████████████████████▌   | 38.7M/43.0M [00:06<00:00, 7.57MB/s]
Voucher file saved to /home/ubuntu/hpmor/Harry_Potter_and_The_Methods_of_Rationality_Audiobook/Harry_Potter_and_The_Methods_of_Rationality_Audiobook_Chapter_122_Something_to_Protect_Hermione_Granger-MPEG.voucher.

[More logs: there are more than 100 episodes in total]
```
