### ISSUE TITLE
Max Queries

### ISSUE THREAD

**Issue by johnlescault** [mkb79/audible-cli#60]
I think Audible may have just put in a max amount of queries.

In my library that is close to 1500 books, just running a "audible download --all --aaxc --cover --cover-size 1215 --chapter --pdf --jobs 3" eventually turns into the following error "Error in job: Forbidden (403): Customer [XXXXXXXXXXXX] is above threshold for content license grant count". (Even if I already have most of the books its querying it seems like it counts them)

If you wanted to know the max amount of books it can do before starting that I think I would need an option to show what book # you are at in the library.

Following that would it be possible to create an option to "Wait after X amount of books for X minutes"?

Thanks so much for this tool.

**Comment by mkb79** [comment]
Hi. This is a problem when you using the `--all` with the `--aaxc` flag. Internally audible-cli makes a `licenserequest` for every item to got the provided codec. The codec is needed to build the filename. After that audible-cli checks, if a file with these name exists and skip it, if so. 

I‘ll have to find out a way to check if the file exists without making the `licenserequest`. So you can download all files in bunches with a cooldown between them. 

In the meantime I can build a counter for you which count the number on licenserequests. Would you test this for me if it is finished?

**Comment by johnlescault** [comment]
I can of course test this for you. Just give me the steps on how to update properly please when its ready!
Thanks again!

**Comment by mkb79** [comment]
I‘ve commit a change to development branch which avoid a `licenserequest` if the aaxc and the voucher files exist. 

Best is to clone it into a new directory with `git clone --branch development https://github.com/mkb79/audible-cli`. Then switch to the new directory and run `pip3 install --upgrade .`! Please check with `audible-cli --version` that you are running v0.1.0b4!

As a good solution I would prefer to use venv. So you can test this and leave your running system untouched!

**Comment by mkb79** [comment]
The reason for this is, you installed audible-cli over your production system. On this you have audible-series installed. If you use venv, this would not be happen. 

Please execute the same command with `--timeout=0` option.

**Comment by johnlescault** [comment]
Added the --timeout=0. this time got this error:

```
--- Logging error ---
Traceback (most recent call last):
  File "/home/joey/.local/lib/python3.8/site-packages/audible/client.py", line 265, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/httpx/_models.py", line 1507, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'https://api.audible.com/1.0/library?image_sizes=1215%2C+408%2C+360%2C+882%2C+315%2C+570%2C+252%2C+558%2C+900%2C+500&response_groups=contributors%2C+customer_rights%2C+media%2C+price%2C+product_attrs%2C+product_desc%2C+product_extended_attrs%2C+product_plan_details%2C+product_plans%2C+rating%2C+sample%2C+sku%2C+series%2C+reviews%2C+ws4v%2C+origin%2C+relationships%2C+review_attrs%2C+categories%2C+badge_types%2C+category_ladders%2C+claim_code_url%2C+in_wishlist%2C+is_archived%2C+is_downloaded%2C+is_finished%2C+is_playable%2C+is_removable%2C+is_returnable%2C+is_visible%2C+listening_status%2C+order_details%2C+origin_asin%2C+pdf_url%2C+percent_complete%2C+periodicals%2C+provided_review%2C+product_details&page=2&num_results=1000'
For more information check: https://httpstatuses.com/500

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joey/.local/lib/python3.8/site-packages/audible_cli/cli.py", line 69, in main
    sys.exit(cli(*args, **kwargs))
  File "/home/joey/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/joey/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/joey/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/joey/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/joey/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/joey/.local/lib/python3.8/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/joey/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/joey/.local/lib/python3.8/site-packages/audible_cli/cmds/cmd_download.py", line 560, in cli
    loop.run_until_complete(main(config, auth, **params))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/joey/.local/lib/python3.8/site-packages/audible_cli/cmds/cmd_download.py", line 345, in main
    library = await Library.get_from_api(
  File "/home/joey/.local/lib/python3.8/site-packages/audible_cli/models.py", line 354, in get_from_api
    resp = await fetch_library(request_params)
  File "/home/joey/.local/lib/python3.8/site-packages/audible_cli/models.py", line 345, in fetch_library
    r = await api_client.get("library", params=params)
  File "/home/joey/.local/lib/python3.8/site-packages/audible/client.py", line 279, in _request
    self._raise_for_status_error(exc.response)
  File "/home/joey/.local/lib/python3.8/site-packages/audible/client.py", line 115, in _raise_for_status_error
    raise UnexpectedError(resp, data)
audible.exceptions.UnexpectedError: Internal Server Error (500): <html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>We're sorry!</title>
</head>

<body style="padding: 4em; color: black; background-color: white; font-family: Verdana,Arial,Helvetica,sans-serif;">

<h2>We're sorry!</h2>
<p>
An error occurred when we tried to process your request.
Rest assured, we're already working on the problem and expect to resolve it shortly.
</p>

<h2>Désolés!</h2>
<p>
Une erreur s'est produite lorsque nous avons tenté de traiter votre requête.
Soyez assuré que nous travaillons déjà à la résolution du problème que nous pensons trouver très rapidement.
</p>

</body>
</html>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joey/.local/lib/python3.8/site-packages/audible_cli/_logging.py", line 127, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/home/joey/.local/lib/python3.8/site-packages/audible_cli/_logging.py", line 117, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib/python3.8/logging/__init__.py", line 669, in format
    if self.usesTime():
  File "/usr/lib/python3.8/logging/__init__.py", line 637, in usesTime
    return self._style.usesTime()
AttributeError: 'ColorFormatter' object has no attribute '_style'
Call stack:
  File "/home/joey/.local/bin/audible", line 8, in <module>
    sys.exit(main())
  File "/home/joey/.local/lib/python3.8/site-packages/audible_cli/cli.py", line 77, in main
    logger.exception("Uncaught Exception")
  File "/usr/lib/python3.8/logging/__init__.py", line 1481, in exception
    self.error(msg, *args, exc_info=exc_info, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 954, in handle
    self.emit(record)
  File "/home/joey/.local/lib/python3.8/site-packages/audible_cli/_logging.py", line 134, in emit
    self.handleError(record)
Message: 'Uncaught Exception'
Arguments: ()
```

**Comment by mkb79** [comment]
Okay, I removed the logging exception using `click-log` package. 

But your timeout error is not new. Last time you had an issue with wrong version of installed packages. Maybe you can use `venv` and try again?

**Comment by mkb79** [comment]
@johnlescault In my last update to v0.1.0b5 I‘ve added a download counter for aax, aaxc, voucher (downloaded and saved), pdf, cover and chapter files!

**Comment by johnlescault** [comment]
I agree that the timeout was an issue. I looked into the old ticket you helped me with and you had told me to uninstall and reinstall which had fixed the issue. 

I installed venv (thanks for pushing me, it's about time I start to learn this). When installing audible-cli in there I got the following error:

```
Building wheels for collected packages: audible-cli
  Building wheel for audible-cli (setup.py) ... error
  **ERROR: Command errored out with exit status 1:
   command: /home/joey/env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-fjwc7qr1/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-fjwc7qr1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-6ao0i5cz
       cwd: /tmp/pip-req-build-fjwc7qr1/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for audible-cli**
  Running setup.py clean for audible-cli
Failed to build audible-cli
**ERROR: audible 0.7.0 has requirement httpx==0.20.0, but you'll have httpx 1.0.0b0 which is incompatible.**
Installing collected packages: Pillow, aiofiles, pyasn1, rsa, pyaes, charset-normalizer, idna, rfc3986, sniffio, certifi, anyio, h11, httpcore, httpx, soupsieve, beautifulsoup4, pbkdf2, audible, click, click-log, tabulate, toml, tqdm, audible-cli
    Running setup.py install for audible-cli ... done
Successfully installed Pillow-9.0.1 aiofiles-0.8.0 anyio-3.5.0 audible-0.7.0 audible-cli-0.1.0b5 beautifulsoup4-4.10.0 certifi-2021.10.8 charset-normalizer-2.0.12 click-8.0.4 click-log-0.3.2 h11-0.12.0 httpcore-0.13.7 httpx-1.0.0b0 idna-3.3 pbkdf2-1.3 pyaes-1.6.1 pyasn1-0.4.8 rfc3986-1.5.0 rsa-4.8 sniffio-1.2.0 soupsieve-2.3.1 tabulate-0.8.9 toml-0.10.2 tqdm-4.63.0

```

I did try the command, but it failed I imagine because of that error.  
I downgraded httpx using: sudo python3 -m pip install "httpx==0.20.*"
Re-ran the install still got the error:

```
  ERROR: Command errored out with exit status 1:
   command: /home/joey/env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-qmelgcud/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-qmelgcud/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-rp_44rfh
       cwd: /tmp/pip-req-build-qmelgcud/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for audible-cli
```

Before going too far and me screwing something up, I see setuptools and wheel but can't seem to tell which one i should be installing/upgrading?

**Comment by mkb79** [comment]
If you have activated venv with `source {venv folder}\bin\activate`. Then switch to the cloned `audible-cli` folder and run `pip install --upgrade .`! Between upgrade and the dot is a whitespace!

**Comment by johnlescault** [comment]
Yes that is exaclty what I am doing (env is my venv folder): Copied from the terminal:

(env) joey@Joey-Linux:~/Downloads/audible-cli$ pip3 install --upgrade .

That is what is outputting that error.

**Comment by mkb79** [comment]
Okay then run `pip install --upgrade pip setuptools wheel` with activated venv!

**Comment by mkb79** [comment]
What you can do now is to create and activate a new venv and run `pip install audible`. This should give you the latest stable release. Can you test then again?

**Comment by mkb79** [comment]
Have you a lot podcasts with many episodes?

**Comment by johnlescault** [comment]
I created a new venv, activated it. Only installed audible. No errors on install however it still gave me a time out when running the command. I don't have any podcasts but many books. But I did have the same amount of books this morning and it worked... Nothing has changed in my account.

**Comment by johnlescault** [comment]
Just a thought and I'm not sure if it would solve the issue, but would it be possible to add something like:
audible download book-min=101 book-max=200 to download book 101 to 200 type thing? Or does it have to read the full library everytime?

**Comment by mkb79** [comment]
Yes, this where possible. But I think I will add an `date` option. So the API only returns items added after this date. 

But let us test One thing before. Please pull the latest development branch with `git clone --branch development https://github.com/mkb79/audible-cli `. Change [these](https://github.com/mkb79/audible-cli/blob/cbd942098fc194cf818885bdd109c596d7ddd59d/src/audible_cli/models.py#L340) value from 1.000 to something like 100 or 200. Then create and activate a new venv. Install the newly cloned and adjusted package with `pip install --upgrade pip setuptools wheel` and then `pip install --upgrade pip setuptools wheel`

**Comment by johnlescault** [comment]
Changing it to 200 worked to get it going again! Definately a slower start time but hard to complain if it works! :)  Now that I've learn't how to use venv I will definately be using that from now on. Just as a side question - is it a good idea to create a different venv for every script so that version updates don't interfeer with each other?

So just so I know the change for my own use - the licencerequest is only made if aaxc/voucher exists right? What occurs if the process is stopped half way through a downloaded file? Does it scrap the file?

I don't see the counter so I assume that would be a future upgrade?

Just curious wether you accept donations at all? You've been extremely helpful with this and I'd like to help if possible

**Comment by mkb79** [comment]
> Changing it to 200 worked to get it going again! Definately a slower start time but hard to complain if it works! :)

If you reduce the number to 200 it means, every library request will give you max. 200 items. This reduce the data size to be submit. If you have a slow internet connection you will get a TimeoutError if you don’t get the response in time. The disadvantage is, you must make multiple requests to fetch your entire library! These can't be run async because I doesn't know how much requests (pages) i must do. So you have to wait for the first response, then the client checks if you have 200 items. If so, it makes the next request and so on!
I will implement an option which let you adjust the bunch size!

> Just as a side question - is it a good idea to create a different venv for every script so that version updates don't interfeer with each other?

If you have many venvs, the disadvantage is, you have to activate/deactivate the env if you want to execute different script or command. So I group my scripts/apps where each group have his own venv.

> So just so I know the change for my own use - the licencerequest is only made if aaxc/voucher exists right? What occurs if the process is stopped half way through a downloaded file? Does it scrap the file?

If both files exists no licenserequest is made. If the download of the aaxc file interrupts, it will currently made a new licenserequest if you start again. I can change this behave to only check if the voucher exists, if you want!

> I don't see the counter so I assume that would be a future upgrade?

You will get an overview when your download command finishs. You can get a live counter when you use `audible --v debug download …`. This print out all debug messages!

> Just curious wether you accept donations at all? You've been extremely helpful with this and I'd like to help if possible

Thank you for your offer. But I don’t want any donations. This is my hobby and I'm happy if I can help!!!

**Comment by mkb79** [comment]
Sorry the command is `audible -v debug download …`. Only one `-` before the v!

**Comment by johnlescault** [comment]
Thanks for the quick venv lesson!

> If both files exists no licenserequest is made. If the download of the aaxc file interrupts, it will currently made a new licenserequest if you start again. I can change this behave to only check if the voucher exists, if you want!

No issues with checking both! Probably safer that way?

> You will get an overview when your download command finishs. You can get a live counter when you use audible --v debug download …. This print out all debug messages!

Just tried that - works great! I'm not sure if it's by design or if it's because of the change you made for not checking the library on already downloaded files, but the voucher number only shows "downloaded voucher" and doesn't count the other books that were skipped? To be honest I'm not sure it entirely matters for the most part, but just figured I'd point it out incase you wanted it for troubleshooting purposes.

> Thank you for your offer. But I don’t want any donations. This is my hobby and I'm happy if I can help!!!

If only the software support that I actually paid for was this good...

**Comment by mkb79** [comment]
> No issues with checking both! Probably safer that way?

In my opinion it's safer to check both. But I will implement reuse of downloaded voucher files if the aaxc file is missing. The voucher file contains all information (e.g. download url)! A new licenserequest could be skipped in that case. 

> Just tried that - works great! I'm not sure if it's by design or if it's because of the change you made for not checking the library on already downloaded files, but the voucher number only shows "downloaded voucher" and doesn't count the other books that were skipped? To be honest I'm not sure it entirely matters for the most part, but just figured I'd point it out incase you wanted it for troubleshooting purposes.

There are a counter for downloaded and for saved voucher files. If there are a mismatch between them it will give you a message `Unsaved voucher: NUMBERS` if there where any licenserequests which where not needed (e.g. only voucher file and no aaxc file exist or wrong codec check)! The message appears at the end of all jobs no matters which verbosity option you set! These information are important for troubleshooting purposes!

The option to specify the bunch size is on the way but need some time - it’s weekend ;)!

**Comment by johnlescault** [comment]
No rush for the update - it honestly works great as is!
Enjoy your weekend!

**Comment by mkb79** [comment]
@johnlescault 
I've implemented a `--bunch-size` option to the download, library export and library list subcommands. You can try it with the latest commit in the development branch.

**Comment by johnlescault** [comment]
Sorry I was away for a few days. Just so I get it right:
git clone --branch issue-60 https://github.com/mkb79/audible-cli 
or 
git clone --branch development https://github.com/mkb79/audible-cli

**Comment by mkb79** [comment]
No problem at all. Please use the `development` branch.

**Comment by johnlescault** [comment]
Sorry for the delay. I'm slightly frustrated as it seems I keep doing this wrong...

```
So I created a new venv, activated it.
git clone --branch development https://github.com/mkb79/audible-cli
cd audible-cli
pip install --upgrade pip setuptools wheel (this was required since it was erroring again)
pip install --upgrade .
```

then when i run:

`audible -v debug download --all --aaxc --cover --cover-size 1215 --chapter --pdf --jobs 3 --bunch-size 500
debug: Audible-cli version: 0.1.0b5
debug: App dir: /home/joey/.audible
debug: Plugin dir: /home/joey/.audible/plugins
Usage: audible download [OPTIONS]
Try 'audible download -h' for help.

Error: No such option: --bunch-size Did you mean --cover-size?
`

**Comment by mkb79** [comment]
Please use released version v0.1.0 from PyPI. This have the `--bunch-size` option!

**Comment by johnlescault** [comment]
Seems to be working. Only change I saw from previous dev is this doesn't show anymore:
Fetching library page 1 with bunch size 200
Fetching library page 2 with bunch size 200
Fetching library page 3 with bunch size 200

I don't think it matters if it doesn't show, but just mentioning it incase it wasn't intentional.

Thanks again !

**Comment by mkb79** [comment]
I‘ve added this line for development purposes. I thought no one is interested in this information, so I removed them.

I'm thinking about adding more debugging output. Since adding the `--verbosity` option, this should not end in a pain for regular users!
