### ISSUE TITLE
pyinstall isn't valid python3

### ISSUE THREAD

**Issue by philgoetz** [mkb79/audible-cli#64]
The instructions for compiling audible-cli rely on pyinstall.
pyinstall isn't an executable, so I assume they should say

pyinstall.py audible.spec

But pyinstall doesn't work with python 3.
It gives errors like

```
$ pyinstall.py audible.spec
  File "/usr/local/bin/pyinstall.py", line 242
    print 'Running in environment %s' % options.venv
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Running in environment %s' % options.venv)?
```

and

```
$ pyinstall.py audible.spec
  File "/usr/local/bin/pyinstall.py", line 314
    except InstallationError, e:
                            ^
SyntaxError: invalid syntax
```

The README.md says this requires Python 3.6, so I must be doing something wrong; but all I did was follow the instructions.
I suppose my python somehow has multiple versions of pyinstall installed,
particularly as I see this:

$ pip install pyinstall
Requirement already satisfied: pyinstall in /usr/local/lib/python3.8/site-packages (0.1.4)

$ python --version
Python 3.9.10

I'm very new to python, and don't know how to get my pip working with my python.

UPDATE: The version of pyinstall.py in my python3.8 is in fact v0.1.4, the latest version, and isn't valid python3 code.

UPDATE:  I was able to use pyinstaller rather than python.  Apparently pyinstaller is a replacement for pyinstall.  But in my Cygwin Python3.8, it choked on the python module pywin32, which it couldn't find anywhere to install.
Then I used the Python 3.9 installed by IDLE, which was able to find pywin32 and run pyinstaller.
I am now mysteriously able to use audible-cli from the command line in cygwin, even though I didn't install it in cygwin's Python.

**Comment by mkb79** [comment]
Thank you for open this issue. I'm really sorry to waste your time. The command name is `pyinstaller` instead of `pyinstall`. I've fixed that!

**Comment by mkb79** [comment]
Can I close this issue now?
