### ISSUE TITLE
links to Windows executables are broken

### ISSUE THREAD

**Issue by philgoetz** [mkb79/audible-cli#65]
There is no such page
https://github.com/mkb79/audible-cli/releases/download/latest/audible_win_dir.zip
or
https://github.com/mkb79/audible-cli/releases/download/latest/audible_win.zip

I found
https://github.com/mkb79/audible-cli/releases/download/v0.1.0/audible_win.zip

but note this isn't the URL in the README.

**Comment by mkb79** [comment]
That’s really strange. My links reference always to the latest release. Your link reference to release v0.1.0! But v0.1.0 is the latest at this time! I've use the latest syntax, so I don’t need to update the README (or forget it) on every new release. 

In some internet guides I read about the latest syntax! And all links worked for me (using Safari on iOS or Chrome on Windows). So I does not take look deeper into this. Maybe I remove the links and will only link to the releases page.

**Comment by philgoetz** [comment]
Sounds like it's a bug in github.

**Comment by mkb79** [comment]
[Here](https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases) I found the official documentation to download the latest release asset. This is what I've done!

**Comment by mkb79** [comment]
Oh, I saw my mistake! I will fix this!
