### ISSUE TITLE
audible.exe for windows has 13 hits on virustotal

### ISSUE THREAD

**Issue by philgoetz** [mkb79/audible-cli#66]
I downloaded audible_win.zip, and virustotal.com had [13 hits](https://www.virustotal.com/gui/file/bb38fad177cf5b25feef9fe72e4bc7961dda4c06402dbf4d7f6bd0d4862dce84?nocache=1) to virus signatures for the standalone audible.exe.

I downloaded audible_win_dir.zip, and its audible.exe had [4 hits](https://www.virustotal.com/gui/file/01ef5dbdb7695f3a9fbca97fb50e68820aa7dcc25a331ffda9a5c3a2fa3dd181?nocache=1).

According to some google hits, this is probably due to pyinstaller.

**Comment by mkb79** [comment]
Except one, all release assets are build with GitHub actions using [this](https://github.com/mkb79/audible-cli/blob/master/.github/workflows/build.yml) script. So I don’t take any dangerous code in it.

**Comment by mkb79** [comment]
Can I close this issue now?
