### ISSUE TITLE
Failure to download audiobooks included with Audible subscription

### ISSUE THREAD

**Issue by philgoetz** [mkb79/audible-cli#67]
Some books are available for free with an Audible subscription or an Amazon Prime subscription.
These books aren't marked in any special way on the Android app, but say "Included" when viewing your library using the Windows app.  They give an error message like this:

```
$ audible download -a B0189JVZ1G -aaxc --cover --cover-size 1215 --chapter -q normal --pdf
error: Asin axc not found in library.
error: Skip asin axc: Not found in library
Chapter file saved to /home/brek/.audible/Unbound_How_Eight_Technologies_Made_Us_Human_Transformed_Society_and_Brought_Our_World_to_the_Brink-chapters.json.
File /home/brek/.audible/Unbound_How_Eight_Technologies_Made_Us_Human_Transformed_Society_and_Brought_Our_World_to_the_Brink_(1215).jpg downloaded to /home/brek/.audible in 0:00:00.247749.
File /home/brek/.audible/Unbound_How_Eight_Technologies_Made_Us_Human_Transformed_Society_and_Brought_Our_World_to_the_Brink.pdf downloaded to /home/brek/.audible in 0:00:03.707639.
The download ended with the following result:
New chapter files: 1
New cover files: 1
New pdf files: 1
```

It retrieves the cover, chapter info, and the PDF, but not the aaxc.  I get the same results using -aax instead of -aaxc.

Some audiobooks are, for some reason, only available temporarily.  On the Android audible app, these have an orange notice under them saying something like "Available until 5/18".   If I recall, there's no indication using the Windows app when one of your files is for some reason going to be removed at a future date.  These give an error like this:

```$ audible download -a B07C553PN9 --aaxc --cover --cover-size 1215 --chapter -q normal --pdf
File /home/brek/.audible/Against_Interpretation_and_Other_Essays_(1215).jpg already exists. Skip download
No PDF found for Against Interpretation and Other Essays
File /home/brek/.audible/Against_Interpretation_and_Other_Essays-chapters.json already exists. Skip saving chapters
AAX_44_64 codec was not found, using AAX_22_64 instead
error: 'content_url'
No new files downloaded.
```

The Audible server obviously handles these files differently, and it would probably be a lot of work to retrieve them.  It isn't hugely important to me for audible-cli to download them.  But the documentation should probably mention that it won't, in case someone wants to use it specifically to download such files.

**Comment by mkb79** [comment]
I‘ve tried it with asin `B0189JVZ1G`. Added this item to my library first. I‘ve got the same `Not found in library` error when downloading via `--aax`. But downloading with `--aaxc` works like a charm!

Can you explain me your second issue with other words. I does not understand what you mean with this. I can’t test this myself, because `B07C553PN9` is not free! 

FYI:
You can use `audible -v error` to reduce the output to errors. This would help next time.

**Comment by mkb79** [comment]
For asin `B0189JVZ1G` I've got this response:

```python
plans = [{'customer_eligible': None, 'detail_plan_names': None, 'end_date': '2099-12-31T00:00:00.000-00:00', 'plan_name': 'Rodizio', 'start_date': '2020-09-01T00:00:00.000-00:00'}, {'customer_eligible': True, 'detail_plan_names': None, 'end_date': '2099-12-31T12:00:00.00000Z', 'plan_name': 'US Minerva', 'start_date': '2020-07-02T01:53:00.00053Z'}, {'customer_eligible': None, 'detail_plan_names': None, 'end_date': '2022-04-17T16:24:37.531Z', 'plan_name': 'SpecialBenefit', 'start_date': '2022-03-17T16:24:37.531Z'}]

customer_rights = {'is_consumable': True, 'is_consumable_indefinitely': False, 'is_consumable_offline': True, 'is_consumable_until': '2099-12-31T12:00:00Z'}
```

And for another book, which I can download via `--aax` I've got:

```python 
plans = []
customer_rights = {'is_consumable': True, 'is_consumable_indefinitely': True, 'is_consumable_offline': True, 'is_consumable_until': None}
```

So I think I can implement a check for is_consumable_until of the customer_rights and if there are a plan or not.

**Comment by philgoetz** [comment]
> I‘ve tried it with asin `B0189JVZ1G`. Added this item to my library first. I‘ve got the same `Not found in library` error when downloading via `--aax`. But downloading with `--aaxc` works like a charm!

It makes sense that you can download the aaxc but not the aax, because these free titles can be downloaded on Android as aaxc, but can only be streamed, not downloaded, with the Windows app.

Aha!

`$ audible download -a B0189JVZ1G -aaxc
error: Please select an option what you want download.
error: Asin axc not found in library.
error: Skip asin axc: Not found in library
No new files downloaded.
`

I see from the error messages that it's reading "-aaxc" as "-a axc". When I use --aaxc instead, it works.  My mistake!

**Comment by mkb79** [comment]
Can I close this issue now?

**Comment by philgoetz** [comment]
> Can I close this issue now?

Oh, right, I'll close it now.
