### ISSUE TITLE
"peer closed connection without sending complete message body)

### ISSUE THREAD

**Issue by jpretori** [mkb79/audible-cli#76]
I tried downloading a few books, but I always seem to get this message.

Help?
```

error: peer closed connection without sending complete message body (received 18030257 bytes, expected 44054745)
No new files downloaded.

```

**Comment by mkb79** [comment]
Hi. This seams to be a timeout issue. You can try to use `--timeout 0` to disable timeout and/or `--jobs 1` to only process one time at a time.

**Comment by jpretori** [comment]
Thanks!  That seems to help in some cases.  I still get problems though:

```
$ audible download -t Children --aax -y --timeout 0 --jobs 1

Found the following matches for 'Children'
+---------+------------------+------------+
| % match | title            |    asin    |
+---------+------------------+------------+
|  100.0  | Children of Time | B071Y9TTHC |
+---------+------------------+------------+
Children_of_Time-LC_64_22050_stereo.aax:   1%|▊                                                                                                         | 3.76M/459M [00:49<1:40:39, 79.0kB/s]
error: peer closed connection without sending complete message body (received 3941559 bytes, expected 481025180)
No new files downloaded.

```

**Comment by mkb79** [comment]
Which version of `audible-cli` and `httpx` you use? Do you use a standalone binary of `audible-cli`?

**Comment by jpretori** [comment]
`$ audible --version
audible-cli, version 0.1.3 (up-to-date)`

I installed it using pip a few hours ago.

Interestingly, when I tried to run httpx to get a CLI help printout so I could ask for its version, it said: 

`$ httpx --version
The httpx command line client could not run because the required dependencies were not installed.
Make sure you've installed everything with: pip install 'httpx[cli]'`

So I did that, and got:

`$ pip install httpx[cli]
Requirement already satisfied: httpx[cli] in ./.local/lib/python3.8/site-packages (0.20.0)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from httpx[cli]) (2019.11.28)
Requirement already satisfied: sniffio in ./.local/lib/python3.8/site-packages (from httpx[cli]) (1.2.0)
Requirement already satisfied: charset-normalizer in ./.local/lib/python3.8/site-packages (from httpx[cli]) (2.0.9)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in ./.local/lib/python3.8/site-packages (from httpx[cli]) (1.5.0)
Requirement already satisfied: httpcore<0.14.0,>=0.13.3 in ./.local/lib/python3.8/site-packages (from httpx[cli]) (0.13.7)
Requirement already satisfied: pygments==2.*; extra == "cli" in /usr/lib/python3/dist-packages (from httpx[cli]) (2.3.1)
Collecting rich==10.*; extra == "cli"
  Downloading rich-10.16.2-py3-none-any.whl (214 kB)
     |████████████████████████████████| 214 kB 8.9 MB/s 
Requirement already satisfied: click==8.*; extra == "cli" in ./.local/lib/python3.8/site-packages (from httpx[cli]) (8.1.2)
Requirement already satisfied: idna; extra == "idna2008" in /usr/lib/python3/dist-packages (from rfc3986[idna2008]<2,>=1.3->httpx[cli]) (2.8)
Requirement already satisfied: h11<0.13,>=0.11 in ./.local/lib/python3.8/site-packages (from httpcore<0.14.0,>=0.13.3->httpx[cli]) (0.12.0)
Requirement already satisfied: anyio==3.* in ./.local/lib/python3.8/site-packages (from httpcore<0.14.0,>=0.13.3->httpx[cli]) (3.4.0)
Collecting commonmark<0.10.0,>=0.9.0
  Downloading commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
     |████████████████████████████████| 51 kB 11.0 MB/s 
Requirement already satisfied: colorama<0.5.0,>=0.4.0 in /usr/lib/python3/dist-packages (from rich==10.*; extra == "cli"->httpx[cli]) (0.4.3)
ERROR: rich 10.16.2 has requirement pygments<3.0.0,>=2.6.0, but you'll have pygments 2.3.1 which is incompatible.
Installing collected packages: commonmark, rich
Successfully installed commonmark-0.9.1 rich-10.16.2`

Which I think means I now have v0.20.0.  

So I tried again, but to no avail:  `No new files downloaded`

**Comment by jpretori** [comment]
So I did `pip  install rich`, which installed a different version of `rich` (I think).  Trying again now.

**Comment by mkb79** [comment]
You can try to bump httpx to v0.22.0 with `pip install --upgrade httpx`. httpx>=0.21.0 uses a higher version of httpcore. Maybe this helps out.

**Comment by jpretori** [comment]
My plan didn't work, so I tried yours.  I got:

```
$ pip install --upgrade httpx
Collecting httpx
  Downloading httpx-0.22.0-py3-none-any.whl (84 kB)
     |████████████████████████████████| 84 kB 4.0 MB/s 
Collecting httpcore<0.15.0,>=0.14.5
  Downloading httpcore-0.14.7-py3-none-any.whl (68 kB)
     |████████████████████████████████| 68 kB 9.5 MB/s 
Requirement already satisfied, skipping upgrade: certifi in /usr/lib/python3/dist-packages (from httpx) (2019.11.28)
Requirement already satisfied, skipping upgrade: sniffio in /home/johan/.local/lib/python3.8/site-packages (from httpx) (1.2.0)
Requirement already satisfied, skipping upgrade: charset-normalizer in /home/johan/.local/lib/python3.8/site-packages (from httpx) (2.0.9)
Requirement already satisfied, skipping upgrade: rfc3986[idna2008]<2,>=1.3 in /home/johan/.local/lib/python3.8/site-packages (from httpx) (1.5.0)
Requirement already satisfied, skipping upgrade: h11<0.13,>=0.11 in /home/johan/.local/lib/python3.8/site-packages (from httpcore<0.15.0,>=0.14.5->httpx) (0.12.0)
Requirement already satisfied, skipping upgrade: anyio==3.* in /home/johan/.local/lib/python3.8/site-packages (from httpcore<0.15.0,>=0.14.5->httpx) (3.4.0)
Requirement already satisfied, skipping upgrade: idna; extra == "idna2008" in /usr/lib/python3/dist-packages (from rfc3986[idna2008]<2,>=1.3->httpx) (2.8)
ERROR: audible 0.7.2 has requirement httpx==0.20.0, but you'll have httpx 0.22.0 which is incompatible.
ERROR: audible-cli 0.1.3 has requirement httpx==0.20.*, but you'll have httpx 0.22.0 which is incompatible.
Installing collected packages: httpcore, httpx
  Attempting uninstall: httpcore
    Found existing installation: httpcore 0.13.7
    Uninstalling httpcore-0.13.7:
      Successfully uninstalled httpcore-0.13.7
  Attempting uninstall: httpx
    Found existing installation: httpx 0.20.0
    Uninstalling httpx-0.20.0:
      Successfully uninstalled httpx-0.20.0
Successfully installed httpcore-0.14.7 httpx-0.22.0
```

**Comment by mkb79** [comment]
The error message is okay. httpx 0.22.0 will work with `audible-cli`. Now you can try to download again with timeout 0 and jobs 1!How fast is your internet speed?

**Comment by jpretori** [comment]
I have fibre, 35MBps download speed.   I'm getting _atrocious_ speeds from Audible though.  It looks like it mostly runs at 200 - 300 kB/s... some downloads are running at 20 - 40 kB/s at the time when they break.

I kicked off another attempt before you posted.  I specified timeout 0, but didn't say anything about the number of jobs... looks like it defaults to 3.  That didn't work, so I tried again with jobs 1.  Lets see how that goes.

**Comment by jpretori** [comment]
I don't suppose there's any way to have it resume a download that broke partway through?

**Comment by mkb79** [comment]
> I kicked off another attempt before you posted. I specified timeout 0, but didn't say anything about the number of jobs... looks like it defaults to 3. That didn't work, so I tried again with jobs 1. Lets see how that goes.

By default `audible-cli` runs 3 jobs asynchronous. In that case your bandwidth is split between the downloads. This result in a slow download speed per job. This can be solved with `--jobs 1`. 

> I don't suppose there's any way to have it resume a download that broke partway through?

I doesn’t know if the Audible servers support download resume. If yes, it could be possible to implement. But I need to rework `audible-cli` for supporting this on client side. 

My next question is about the Audible marketplace you use?! Is your country far away from the marketplace you use?

**Comment by jpretori** [comment]
OK I tried with `--jobs 1` - the download speed is definitely better, but the downloads are still breaking.  One got as far as 88MB.

I'm in South Africa, the marketplace is in the US.

**Comment by mkb79** [comment]
> I'm in South Africa, the marketplace is in the US

Maybe that’s the reason for your slow download speed. Have you the same issues when downloading the files with your web browser?

Maybe there is a problem with your Python installation. You can try a standalone binary from my releases page. This will bring all dependencies in one file (Python interpreter, packages and so on)!

**Comment by jpretori** [comment]
> Maybe that’s the reason for your slow download speed. Have you the same issues when downloading the files with your web browser?

Yes... that's why I went hunting for an alternative tool in the first place.  I have no issues with any other websites or tools.  Yesterday I finally managed to download one book at attempt number 13 :(

I'll try the full binary.

**Comment by jpretori** [comment]
> I'll try the full binary.

Same problem.

**Comment by mkb79** [comment]
I‘m really sorry about your issue. Maybe I find a another solution. So I will let open your issue for some time.

**Comment by jpretori** [comment]
I have something that is perhaps interesting: I tried with `--quality high` (which I believe is one notch down from the default).  I still have `--jobs ` and `--timeout 0`.

The downloads are still breaking, but they are getting a lot further.  Maybe I'll take the quality another notch down later if it seems necessary to achieve a full download.

**Comment by jpretori** [comment]
Interesting, when the last download broke at 147/938M, it gave this error: 

```
error: peer closed connection without sending complete message body (received 153759723 bytes, expected 983677835)
AAX_44_128 codec was not found, using AAX_22_64 instead
```
Is it significant?  This is with --quality high

**Comment by mkb79** [comment]
Oh, you can try to download the with `--aaxc` flag and not `--aax`! This will download the aaxc file from another server than the aax file. Ffmpeg >= 4.4 can decrypt aaxc files!

**Comment by jpretori** [comment]
Heh :-D  OK I'll try that.

**Comment by mkb79** [comment]
The quality option `best` only means selecting the best available codec. For most cases this is the `high` quality codec `AAX_44_128`. The normal codec is `AAX_44_64`.

**Comment by jpretori** [comment]
I tried that, after some digging around to get ffmpeg upgraded. 

There's something going on with .voucher files that I don't understand, but (a) the downloads are using the full ~4000 kB/s that my connection has available, and (b) it appears I'm getting complete downloads now!

Right now I'm staring at a terminal window where AAXtoMP3 is using ffmpeg to decode one of the new aaxc files.  Looks like it worked!

Thank you very much.

**Comment by mkb79** [comment]
> There's something going on with .voucher files that I don't understand

What’s going on? How can I help you?

> Right now I'm staring at a terminal window where AAXtoMP3 is using ffmpeg to decode one of the new aaxc files. Looks like it worked!

AAXtoMP3 works with aaxc files downloaded with `audible-cli`. 

FYI:
I had some troubles downloading PDF files with `audible-cli` after you opened the issue. Now all works like it should. Maybe some Audible servers had some issues yesterday!

**Comment by jpretori** [comment]
With the .voucher files, only that they exist and I don't understand what they are :-)

Everything seems to work now, except that AAXtoMP3 only pulls 3MB worth of chapters out of the 980GB aaxc file... I opened an issue for that in that GitHub repo.

Thanks for all your help!

**Comment by mkb79** [comment]
The `voucher` file contains the `IV` and `KEY` to decrypt the aaxc file. Instead of `aax` files, which all can be decoded with the same `activation bytes`, the `IV` and `KEY` are unique for every file.

**Comment by jpretori** [comment]
Short summary for people finding this later on:  Turns out the problem was probably related to bandwidth and download speed.  

Fixed it by:
1. Download the .aaxc files instead of the .aax files.  These seem to be in a different geography, and download speeds and reliability shot up to normal levels
2. Upgrade to ffmpeg 4.4 by adding the appropriate PPA - I am running Mint.
3. Use AAXtoMP3 to convert the aaxc files to mp3.  Unfortunately there seems to be a problem left, in that it doesn't deal with chaptered output properly: https://github.com/KrumpetPirate/AAXtoMP3/issues/215
