### ISSUE TITLE
‘Error: no such option: -B’ when downloading with -t flag

### ISSUE THREAD

**Issue by LwsBtlr** [mkb79/audible-cli#78]
MacOS 12.3, M1 (ARM)

`audible download -y -a <ASIN> --aax` Works fine, and downloads at well over 5MB/s with no issue.

Changing to ‘-a Relentless’ yields

```
The_Relentless_Moon_Lady_Astronaut_Book_3-LC_64_44100_stereo.aax:   0%|▏                                       | 1.83M/490M [00:04<24:46, 344kB/s]Usage: audible [OPTIONS] COMMAND [ARGS]...
Try 'audible -h' for help.

Error: No such option: -B
The_Relentless_Moon_Lady_Astronaut_Book_3-LC_64_44100_stereo.aax:  11%|████▎                                   | 53.5M/490M [02:46<50:03, 152kB/s]```

And then the download fails to complete (after struggling for a bit very very slowly)

**Comment by mkb79** [comment]
The `-a / --asin` only accept a [asin](https://en.m.wikipedia.org/wiki/Amazon_Standard_Identification_Number) and not a title like `Relentless`. You can download items via title with the `-t / --title` option. If the title contains whitespace, you have to surround them with double quotes. So you have to use `audible download -t Relentless --aax -y`.

**Comment by LwsBtlr** [comment]
sorry, that was a typo on my part. Changing to `-t Relentless` I R Dum.

**Comment by mkb79** [comment]
Maybe you can use double quotes like `-t "Relentless"` with the downloaded executable.

**Comment by tomhoover** [comment]
macOS Ventura 13.6 (22G120), MacBook Pro (M1)

I can confirm the error message `Error: No such option: -B` appears when using the downloaded executable (https://github.com/mkb79/audible-cli/releases/download/v0.2.5/audible_mac.zip), _but not when installing audible-cli via pip_. It appears when using either the `-a / --asin` or the `-t / --title` options. It also appears with `--aax`, `--aaxc`, or `--aax-fallback`. In each case, asins/titles are in double-quotes.

For example:
`audible download --output-dir dl --asin "B008PGDT04" --aaxc --pdf --cover --chapter --annotation --no-confirm --overwrite --ignore-errors`
produces:
```
No PDF found for A Perfect Spy: A Novel
No annotations found for A Perfect Spy: A Novel.
File /Users/tom/data/books/audible/dl/A_Perfect_Spy_A_Novel_(500).jpg downloaded in 0:00:00.294011.
Chapter file saved to /Users/tom/data/books/audible/dl/A_Perfect_Spy_A_Novel-chapters.json.
Voucher file saved to /Users/tom/data/books/audible/dl/A_Perfect_Spy_A_Novel-AAX_22_64.voucher.
A_Perfect_Spy_A_Novel-AAX_22_64.aaxc:   3%|█                 | 14.5M/580M [00:04<03:16, 3.01MB/s]
Usage: audible [OPTIONS] COMMAND [ARGS]...
Try 'audible -h' for help.

Error: No such option: -B
A_Perfect_Spy_A_Novel-AAX_22_64.aaxc: 100%|██████████████████| 580M/580M [03:25<00:00, 2.96MB/s]
File /Users/tom/data/books/audible/dl/A_Perfect_Spy_A_Novel-AAX_22_64.aaxc downloaded in 0:03:26.327053.
The download ended with the following result:
New aaxc files: 1
New chapter files: 1
New cover files: 1
New voucher files: 1
```
As you can see, the download appears to abort after a few percent completed, produces the error message, and then resumes. Ultimately, the aax/aaxc file is completely downloaded.

**Comment by tomhoover** [comment]
> 1. Remove the double quotes around the asin.

`audible download --output-dir dl --asin B002V59YC2 --aaxc --pdf --cover --chapter --annotation --no-confirm --overwrite --ignore-errors` displays the same error:
```
No PDF found for The Lincoln Lawyer
Chapter file saved to /Users/tom/data/books/audible/dl/The_Lincoln_Lawyer-chapters.json.
File /Users/tom/data/books/audible/dl/The_Lincoln_Lawyer_(500).jpg downloaded in 0:00:00.356901.
No annotations found for The Lincoln Lawyer.
Voucher file saved to /Users/tom/data/books/audible/dl/The_Lincoln_Lawyer-AAX_44_128.voucher.
The_Lincoln_Lawyer-AAX_44_128.aaxc:   2%|██▋                | 15.4M/642M [00:05<03:36, 3.04MB/s]
Usage: audible [OPTIONS] COMMAND [ARGS]...
Try 'audible -h' for help.

Error: No such option: -B
The_Lincoln_Lawyer-AAX_44_128.aaxc: 100%|██████████| 642M/642M [04:06<00:00, 2.73MB/s]
File /Users/tom/data/books/audible/dl/The_Lincoln_Lawyer-AAX_44_128.aaxc downloaded in 0:04:06.658223.
The download ended with the following result:
New aaxc files: 1
New chapter files: 1
New cover files: 1
New voucher files: 1
audible download --output-dir dl --asin B002V59YC2 --aaxc --pdf     37.58s user 9.99s system 18% cpu 4:14.46 total
```
> 2. Provide an asin which starts with another letter or string except „B“.

`audible download --output-dir dl --asin 0062990187 --aaxc --pdf --cover --chapter --annotation --no-confirm --overwrite --ignore-errors` displays the same error:
```
No PDF found for The Infinite Machine: How an Army of Crypto-Hackers Is Building the Next Internet with Ethereum
Chapter file saved to /Users/tom/data/books/audible/dl/The_Infinite_Machine_How_an_Army_of_Crypto-Hackers_Is_Building_the_Next_Internet_with_Ethereum-chapters.json.
File /Users/tom/data/books/audible/dl/The_Infinite_Machine_How_an_Army_of_Crypto-Hackers_Is_Building_the_Next_Internet_with_Ethereum_(500).jpg downloaded in 0:00:00.281601.
Voucher file saved to /Users/tom/data/books/audible/dl/The_Infinite_Machine_How_an_Army_of_Crypto-Hackers_Is_Building_the_Next_Internet_with_Ethereum-AAX_44_128.voucher.
Annotation file saved to /Users/tom/data/books/audible/dl/The_Infinite_Machine_How_an_Army_of_Crypto-Hackers_Is_Building_the_Next_Internet_with_Ethereum-annotations.json.
The_Infinite_Machine_How_an_Army_of_Crypto-Hackers_Is_Building_the_Next_Internet_with_Ethereum-AAX_44_128.aaxc:   2%|▌                                   | 9.06M/583M [00:04<04:16, 2.35MB/s]
Usage: audible [OPTIONS] COMMAND [ARGS]...
Try 'audible -h' for help.

Error: No such option: -B
The_Infinite_Machine_How_an_Army_of_Crypto-Hackers_Is_Building_the_Next_Internet_with_Ethereum-AAX_44_128.aaxc: 100%|███████████████████| 583M/583M [03:40<00:00, 2.77MB/s]
File /Users/tom/data/books/audible/dl/The_Infinite_Machine_How_an_Army_of_Crypto-Hackers_Is_Building_the_Next_Internet_with_Ethereum-AAX_44_128.aaxc downloaded in 0:03:40.980474.
The download ended with the following result:
New aaxc files: 1
New annotation files: 1
New chapter files: 1
New cover files: 1
New voucher files: 1
audible download --output-dir dl --asin 0062990187 --aaxc --pdf     31.86s user 8.84s system 17% cpu 3:51.94 total
```

**Comment by mkb79** [comment]
Unfortunately, that didn't help. I'll have another idea. Maybe the path resolving of `--output-dir dl` will cause the issue. Can you change your CWD to the `dl` dir and then run the command without the `--output-dir` option. Or maybe you can move the option to the end of your command input. Many thanks.

**Comment by tomhoover** [comment]
Sounds good! I'll be happy to test again once you've made the change(s). As I mentioned before, I'm happily using the pip installed version now, but did want to make you aware of the problem with the standalone executable.
