### ISSUE TITLE
Export -f cover and export -f tab produce the same output

### ISSUE THREAD

**Issue by LwsBtlr** [mkb79/audible-cli#79]
macOS 12.3 M! (ARM)

Both can and tsv format options produce a tab file (the files are identical)

```
 $ diff library.csv library.tsv
 $
```

**Comment by mkb79** [comment]
Hmm, that’s strange. The `csv` output format uses the [excel](https://docs.python.org/3/library/csv.html#csv.excel) dialect and `tsv` uses the [excel-tab](https://docs.python.org/3/library/csv.html#csv.excel_tab) dialect. So there should be a diff between them. I will take a look on this.

**Comment by mkb79** [comment]
I've found out the reason and fixed the bug in the development branch. With release of v0.2.0 this will be fixed.
