### ISSUE TITLE
Feature request: Option to exclude chapter data

### ISSUE THREAD

**Issue by yluvs** [mkb79/audible-cli#92]
Hello, 

Thank you so much for this great program. I've been using it since late 2020 and it just gets better and better!

There is one feature though that I really wish you could consider incorporating into your project. It's the option of excluding chapter data from the voucher file. 

Since we can already obtain this information through the chapter command, I would be very grateful if we could possibly choose whether to include it in the voucher or not.

I really miss the old days when the voucher files were tiny in size and the key & iv appeared in the first two lines. It really was a lot easier to locate the values we needed back then.

Thank you.

**Comment by mkb79** [comment]
@yluvs 
Yeah you are right. The voucher file is really big. I'm with you, to reduce the content to iv and key. But there are three ways:

1. make it optional via an option or
2. make it general and an option, to get the ‚big‘ voucher file or
3. make it general without any option and the chapters can be obtained via `--chapter` flag. 

I would prefer option 1. What do you think?

**Comment by yluvs** [comment]
Thank you so much for the speedy reply, @mkb79 .

I am happy with any of the three. If I have to choose, I would probably go for option 2 or 3 for the reason that we already have the chapter command should we need this data. This way we can keep both voucher and chapter files simple and clean. But just like I said, any of the three is fine with me. ;-)

As always, thank you very much. Have a nice weekend!

**Comment by mkb79** [comment]
@yluvs 
Then I would implement an option like `--basic-voucher` or `--basic-voucher` to save only the iv and key.

**Comment by mkb79** [comment]
@yluvs 
I will implement the second option now!

**Comment by yluvs** [comment]
@mkb79 
That's great! Thank you very much. I really appreciate how quickly you fulfilled this quest. :)
