### ISSUE TITLE
Where do I get the authfile (needed while adding a profile)?

### ISSUE THREAD

**Issue by jpretori** [mkb79/audible-cli#93]
Maybe I'm being dense, but I can't seem to find the answer anywhere online.

I'm trying to add a second profile to audible-cli.  The third question it asks me is `Please enter name for the auth file:`  To this, I do not know how to respond.

I obviously got it right the first time I added a profile, since there in ~/.audible sits my first profile's .json file.  

How do I get the authfile for the second profile?

**Comment by jpretori** [comment]
Actually, I found the answer.

I renamed .audible to something else, then ran quickstart again.  This time there's a whole login sequence that lets me authenticate, answer the captcha and then creates the authfile for me.  

This authentication sequence is missing from `audible manage profile add`.

**Comment by mkb79** [comment]
@jpretori 
The `audible manage profile add` command let you add a new profile to your `config.toml` file in `~/.audible` only. Before you can use a second Audible account with that new profile, you have to run `audible manage auth-file add` first. 

So the correct order is:
1. add a new auth file using your second account
2. add a new profile to your config and use the second auth file

**Comment by jpretori** [comment]
Thanks!  That worked great.  I must have missed that when scanning the CLI output.  Added a short explainer to README in a pull request.

**Comment by mkb79** [comment]
@jpretori 
Thanks for your PR. I've merged it now!
